
let mapOptions = {
  center: [53.825564, -2.421975],
  zoom: 6,
  fullscreenControl: true,
  fullscreenControlOptions: {
      position: 'topleft'
  }
};

let map = new L.map('map' , mapOptions);

let layer = new L.TileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png');
map.addLayer(layer);
   
    // Creates a red marker with the coffee icon

  var redMarker = L.ExtraMarkers.icon({
   prefix: 'fa',
    icon: 'solid fa-sun',
    markerColor: '#d65409',
    iconColor: '#FFD43B',
    svg : true
  });

 // L.marker([51.941196,4.512291], {icon: redMarker}).addTo(map);
  

function addMarker(map, name, position, date, description, url) {

  
let marker = new L.Marker(position, { title: name, icon: redMarker}).addTo(map);

addOpenWindow(marker, name, date, description, url);
 
}

function addOpenWindow(marker, heading, date, description, url) {
  var contentString = "";

  if (url) {
    contentString =
      '<div id="locationContent">' +
      '<div class="eventLocation">' +
      "</div>" +
      '<h2 class="eventTitle">' +
      heading +
      "</h2>" +
      '<div class="eventDate">' +
      date +
      "</div>" +
      '<div class="eventBody">' +
      "<p>" +
      description +
      "</p>" +
      "<p>" +
      '<a href="' +
      url +
      '">Click Here</a> for more information.' +
      "</p>" +
      "</div>" +
      "</div>";
  } else {
    contentString =
      '<div id="locationContent">' +
      '<div class="eventLocation">' +
      "</div>" +
      '<h2 class="eventTitle">' +
      heading +
      "</h2>" +
      '<div class="eventDate">' +
      date +
      "</div>" +
      '<div class="eventBody">' +
      "<p>" +
      description +
      "</p>" +
      "</div>" +
      "</div>";
  }

  marker.bindPopup(contentString);
}
addMarker(map, 'Builth Wells, Wales', {lat: 52.161788,lng: -3.416049}, '13 August 2016', 'Solar Sphere festival workshops with Helen Mason and Emma Wilde (AstroCymru) - 50 students, Key Stage 2 and families');
addMarker(map, 'Seething Astronomy Society, Norwich', {lat: 52.504687,lng: 1.420739}, '30 September 2016', 'Institute of Physics, Norwich, Helen Mason gives a lecture to 50 scientists and members of the public.');
addMarker(map, 'University of Portsmouth, Portsmouth', {lat: 50.795144,lng: -1.093637}, '2 November 2016', 'European Space Education Resource Office (ESERO)/Principia Space Conference - 80 students, Key Stage 2');
addMarker(map, 'University of Portsmouth, Portsmouth', {lat: 50.795144,lng: -1.093737}, '3 November 2016', 'Helen Mason ran Space2Earth workshops with 10 teachers');
addMarker(map, 'University of York, York', {lat: 53.94854,lng: -1.053322}, '4 November 2016', 'European Space Education Resource Office (ESERO)/Principia Space Conference (4-6 November 2016) -  Helen Mason gave public lecture and helped with the Space2Earth stand - reaching 30 students, their families and 10 teachers');
addMarker(map, 'Robert Gordon\'s College, Aberdeen', {lat: 57.148068,lng: -2.101892}, '7 November 2016', 'SunSpaceArt school talk - 40 students, KS4/5 and two teachers');
addMarker(map, 'Robert Gordon\'s College, Aberdeen', {lat: 57.148068,lng: -2.101992}, '7 November 2016', 'Institute of Physics, Aberdeen, Helen Mason gives a lecture to 50 scientists and members of the public.');
addMarker(map, 'Institute for Physics, London', {lat: 51.521737,lng: -0.145293}, '9 November 2016', 'Helen Mason gives keynote address at the Institute of Physics careers for women conference - 50 university students');
addMarker(map, 'Norwich Astronomical Society, Norfolk', {lat: 52.504713,lng: 1.420739}, '18 November 2016', 'Norwich Astronomy Club – Helen Mason gives a public lecture to 50 amateur astronomers');
addMarker(map, 'Shrubland Street Community Primary School, Leamington Spa', {lat: 52.279484,lng: -1.527608}, '8 December 2016', 'Space Camp - Clare Dudeney and Helen Mason run SunSpaceArt workshop - 30 students, Key Stage 2, 3 teachers', 'https://www.sunspaceart.org/school-workshops/space-camp-art/');
addMarker(map, 'Holly Lodge Girls School, Liverpool', {lat: 53.42839,lng: -2.914116}, '14 December 2016', 'Liverpool Fact Art Gallery – ‘Moon Village - Lunar Safety Jackets’ workshop, Holly Lodge Girls School, Year 9, Helen Schell, Deborah Davidson, Ideas Foundation and Helen Mason - 30 students, KS3/4, 5 teachers, KS3, 2 artists', 'https://www.sunspaceart.org/school-workshops/liverpoolfact/');
addMarker(map, 'Bryn Bach Primary School, Wales', {lat: 51.786407,lng: -3.262105}, '10 January 2017', 'Bryn Bach and Fochriw Primary Schools. SunSpaceArt workshop led by Sarah Bridgland and Emma Wride (AstroCymru) , 2 x 2 days and exhibition, 10-11 Jan, 24 Jan, 1 Feb, Key Stage 2, 4 teachers and families', 'https://www.sunspaceart.org/school-workshops/our-3d-universe-wales/');
addMarker(map, 'Fochriw Primary School, Wales', {lat: 51.74269,lng: -3.29568}, '11 January 2017', 'Bryn Bach and Fochriw Primary Schools. SunSpaceArt workshop led by Sarah Bridgland and Emma Wride (AstroCymru) , 2 x 2 days and exhibition, 10-11 Jan, 24 Jan, 1 Feb, Key Stage 2, 4 teachers and families', 'https://www.sunspaceart.org/school-workshops/our-3d-universe-wales/');
addMarker(map, 'Kingsley Community Primary School, Cheshire', {lat: 53.269033,lng: -2.692214}, '24 January 2017', 'SunSpaceArt workshop, run by Geraldine Cox and Clare Dudeney - 30 students, Key Stage 2 and 1 teacher', 'https://www.sunspaceart.org/school-workshops/solar-creativity-kingsley-community-primary-school/');
addMarker(map, 'Scarning Primary School, Norfolk', {lat: 52.67794,lng: 0.918606}, '8 February 2017', '‘Extremophiles’ Space/Art, Scarning Primary School, workshop with SAW Trust, led by UEA undergraduate student, Kirsty Nice and Helen Mason and artist and poet', 'https://www.sunspaceart.org/school-workshops/extremeophiles-in-norfolk/');
addMarker(map, 'Northbury Primary School, London', {lat: 51.541193,lng: 0.075167}, '20 February 2017', 'SunSpaceArt workshop, Helen Mason and Geraldine Cox and Clare Dudeney and Heather MacRae and Urmila Mitra (solar researcher) - 120 students, Key Stage 2 and 6 teachers', 'https://www.sunspaceart.org/school-workshops/sunspaceart-bonanza-in-barking/');
addMarker(map, 'Hockerill Secondary School, Essex', {lat: 51.870138,lng: 0.171052}, '24 February 2017', 'SunSpaceArt workshop From Antarctica to Mars run by Helen Mason, including talk, 90 students, KS3/4 and 6 teachers');
addMarker(map, 'St Ives Scout Group, Cambs', {lat: 52.328378,lng: -0.083497}, '3 March 2017', 'Helen Mason gives talk to St Ives, Scouts group');
addMarker(map, 'Royal Astronomical Society, London', {lat: 51.508665,lng: -0.139506}, '8 March 2017', 'Helen Mason gives a talk on Women in Astronomy for International Women’s Day with 60 members of the public');
addMarker(map, 'Cambridge University, Cambridge', {lat: 52.21011,lng: 0.101204}, '14 March 2017', 'Helen Mason gives a talk at the Cambridge University Astronomy Club to 50 students');
addMarker(map, 'Cambridge Science Festival, Cambridge', {lat: 52.21011,lng: 0.101104}, '21 March 2017', 'Helen Mason gives public lecture to 80 people');
addMarker(map, 'DAMTP, University of Cambridge, Cambridge', {lat: 52.210335,lng: 0.101015}, '25 March 2017', 'DAMTP Open Day');
addMarker(map, 'Northbury Primary School, London', {lat: 51.541193,lng: 0.075067}, '27 March 2017', '2nd visit to Northbury, SunSpaceArt workshop, Helen Mason, Geraldine Cox, Clare Dudeney, Heather MacRae, Urmila Mitra (solar researcher) and Christabel Forbes - 120 students, Key Stage 2 and 6 teachers ', 'https://www.sunspaceart.org/school-workshops/sunspaceart-bonanza-in-barking/');
addMarker(map, 'Society for Popular Astronomy, Cambridge', {lat: 52.214094,lng: 0.095195}, '1 April 2017', 'Helen Mason gives a public lecture to 60 amateur astronomers');
addMarker(map, 'Royal Astronomical Society, London', {lat: 51.508665,lng: -0.139606}, '11 April 2017', 'Helen Mason gives two public lecture to at total of 120 people');
addMarker(map, 'Royal Observatory Greenwich, London', {lat: 51.476873,lng: -0.0005}, '20 April 2017', 'Helen Mason on panel discussion');
addMarker(map, 'Henham and Ugley Primary School, Essex', {lat: 51.929361,lng: 0.249751}, '9 May 2017', 'SunSpaceArt workshop run by Helen Mason and Heather MacRae - 30 students, Key Stage 2', 'https://www.sunspaceart.org/school-workshops/henham-and-ugley-school-essex/');
addMarker(map, 'Bentfield County Primary School, Essex', {lat: 51.909316,lng: 0.193573}, '9 May 2017', 'SunSpaceArt workshop run by Helen Mason and Heather MacRae - 30 students, Key Stage 2', 'https://www.sunspaceart.org/school-workshops/sun-earth-and-moon/');
addMarker(map, 'Highways Primary School, Kent', {lat: 51.359934,lng: 0.111077}, '15 May 2017', 'Flags of the Solar System SunSpaceArt workshop, Helen Schell and Helen Mason  - 30 students, Key Stage 2, two teachers', 'https://www.sunspaceart.org/school-workshops/flags-of-the-solar-system/');
addMarker(map, 'Cambridge International School, Cambridge', {lat: 52.124366,lng: 0.222022}, '17 May 2017', 'Helen Mason gave talk at Assembly - 60 students, Key Stage 3/4 and 5 teachers');
addMarker(map, 'Ely Cathedral, Ely', {lat: 52.398873,lng: 0.26377}, '31 May 2017', 'Science Festival');
addMarker(map, 'UK Space Conference, Liverpool', {lat: 53.395431,lng: -2.990322}, '31 May 2017', 'UK Space Conference, Gala dinner, Helen Mason nominated for an ‘Arthur C. Clarke’ Award for Outreach');
addMarker(map, 'Icknield Primary School, Luton', {lat: 51.909969,lng: -0.434997}, '12 June 2017', 'Helen Mason led assembly with 80 students, Key Stage 1/2 and 10 teachers');
addMarker(map, 'Invicta Grammar School for Girls, Maidstone', {lat: 51.274767,lng: 0.536775}, '26 June 2017', 'Maidstone ‘Festival of Space’ (26-28 June 2017), Heather MacRae (Ideas Foundation), Helen Schell and Jancy McFee (works with NASA) ran workshop - with 34 students, Key Stage 3/4 and 2 teachers ', 'https://www.sunspaceart.org/school-workshops/mission-to-mars-maidstone/');
addMarker(map, 'Valley Park School, Maidstone', {lat: 51.275208,lng: 0.53637}, '26 June 2017', 'Maidstone ‘Festival of Space’ (26-28 June 2017), Heather MacRae (Ideas Foundation), Helen Schell and Jancy McFee (works with NASA) ran workshop - with 34 students, Key Stage 3/4 and 2 teachers ', 'https://www.sunspaceart.org/school-workshops/mission-to-mars-maidstone/');
addMarker(map, 'New Line Learning Academy, Maidstone', {lat: 51.247701,lng: 0.534071}, '27 June 2017', 'Maidstone ‘Festival of Space’ (26-28 June 2017), Heather MacRae (Ideas Foundation), Helen Schell and Jancy McFee (works with NASA) ran workshop - with 34 students, Key Stage 3/4 and 2 teachers ', 'https://www.sunspaceart.org/school-workshops/mission-to-mars-maidstone/');
addMarker(map, 'The Leenham School, Maidstone', {lat: 51.237705,lng: 0.710889}, '27 June 2017', 'Maidstone ‘Festival of Space’ (26-28 June 2017), Heather MacRae (Ideas Foundation), Helen Schell and Jancy McFee (works with NASA) ran workshop - with 34 students, Key Stage 3/4 and 2 teachers ', 'https://www.sunspaceart.org/school-workshops/mission-to-mars-maidstone/');
addMarker(map, 'Cornwallis Academy, Maidstone', {lat: 51.230462,lng: 0.516391}, '28 June 2017', 'Maidstone ‘Festival of Space’ (26-28 June 2017), Heather MacRae (Ideas Foundation), Helen Schell and Jancy McFee (works with NASA) ran workshop - with 34 students, Key Stage 3/4 and 2 teachers ', 'https://www.sunspaceart.org/school-workshops/mission-to-mars-maidstone/');
addMarker(map, 'Broadwater School, Surrey', {lat: 51.201288,lng: -0.594085}, '4 July 2017', '‘SpaceLink’ event and Helen Sharman. Helen Mason gave talk and held workshop with Heather MacRae -  with 80 students, Key Stage 3 and 10 teachers from different schools');
addMarker(map, 'E.A. Milne Centre for Astrophysics, University of Hull, Hull', {lat: 53.771277,lng: -0.36682}, '6 July 2017', 'National Astronomy Meeting 2017 – Astro Outreach - Helen Mason led group at outreach lunch of 60 people from the science and astronomy community');
addMarker(map, 'SolarSphere Festival, Builth Wells, Wales', {lat: 52.161788,lng: -3.416149}, '11 August 2017', 'SolarSphere Festival (11-14 August 2017) - Helen Mason gave a public lecture and ran Space/Art workshops with Emma Wride for 50 students and their families');
addMarker(map, 'Great Smoky Mountains National Park, USA', {lat: 35.566747,lng: -83.500003}, '21 August 2017', 'Total Eclipse of the Sun (17-22 August 2017) - Helen Mason gave a talk as the NASA Solar Expert to 100 families, 200 members of the public and reaching thousands of people on TV NASA 360', 'https://www.sunspaceart.org/school-workshops/solar-eclipse-2017/');
addMarker(map, 'INTERACT, Birmingham', {lat: 52.45113,lng: -1.931719}, '14 September 2017', 'INTERACT - Institute of Physics/STFC/Communicators network - SunSpaceArt display - with 30 science communicators');
addMarker(map, 'Royal Observatory Greenwich, London', {lat: 51.476873,lng: -0.0006}, '14 September 2017', 'Helen Mason – public lecture and podcast');
addMarker(map, 'Armagh Observatory and Planetarium, Northern Ireland', {lat: 54.351879,lng: -6.648574}, '2 October 2017', 'Helen Mason and Geraldine Cox give three workshops to 5 schools (2-3 October 2017) - 200 students, Key Stage 2, and 10 teachers Funded by STFC SPARKS Award to Prof Gerry Doyle', 'https://www.sunspaceart.org/school-workshops/postcards-from-the-solar-system/');
addMarker(map, 'Park, Queen Elizabeth II Primary School, Northern Ireland', {lat: 54.442728,lng: -7.537895}, '2 October 2017', 'Helen Mason and Geraldine Cox give three workshops to 5 schools (2-3 October 2017) - 200 students, Key Stage 2, and 10 teachers Funded by STFC SPARKS Award to Prof Gerry Doyle', 'https://www.sunspaceart.org/school-workshops/postcards-from-the-solar-system/');
addMarker(map, 'St Ronan’s Primary School, Northern Ireland', {lat: 54.595865,lng: -7.226752}, '2 October 2017', 'Helen Mason and Geraldine Cox give three workshops to 5 schools (2-3 October 2017) - 200 students, Key Stage 2, and 10 teachers Funded by STFC SPARKS Award to Prof Gerry Doyle', 'https://www.sunspaceart.org/school-workshops/postcards-from-the-solar-system/');
addMarker(map, 'St Tierney’s Primary School, Northern Ireland', {lat: 54.244455,lng: -7.179482}, '3 October 2017', 'Helen Mason and Geraldine Cox give three workshops to 5 schools (2-3 October 2017) - 200 students, Key Stage 2, and 10 teachers Funded by STFC SPARKS Award to Prof Gerry Doyle', 'https://www.sunspaceart.org/school-workshops/postcards-from-the-solar-system/');
addMarker(map, 'Ballymagee Primary School, Northern Ireland', {lat: 54.64589,lng: -5.634782}, '3 October 2017', 'Helen Mason and Geraldine Cox give three workshops to 5 schools (2-3 October 2017) - 200 students, Key Stage 2, and 10 teachers Funded by STFC SPARKS Award to Prof Gerry Doyle', 'https://www.sunspaceart.org/school-workshops/postcards-from-the-solar-system/');
addMarker(map, 'Orchard County Primary School, Northern Ireland', {lat: 54.457522,lng: -6.607519}, '3 October 2017', 'Helen Mason and Geraldine Cox give three workshops to 5 schools (2-3 October 2017) - 200 students, Key Stage 2, and 10 teachers Funded by STFC SPARKS Award to Prof Gerry Doyle', 'https://www.sunspaceart.org/school-workshops/postcards-from-the-solar-system/');
addMarker(map, 'Ascot Secondary School, Berkshire', {lat: 51.412775,lng: -0.705271}, '11 October 2017', 'Helen Mason Public lecture');
addMarker(map, 'International Astronomy Show, Coventry', {lat: 52.337017,lng: -1.516344}, '12 October 2017', 'International Astronomy Show - Helen Mason gives public lecture to 50 amature astronomers');
addMarker(map, 'Cambridge University Primary School, Cambridge', {lat: 52.219705,lng: 0.088457}, '19 October 2017', 'Ra, the Sun God SunSpaceArt workshop, Helen Schell and Helen Mason - 30 students, Key Stage 2, and 1 teacher', 'https://www.sunspaceart.org/school-workshops/ra-the-sun-god/');
addMarker(map, 'St Edmunds College, Cambridge', {lat: 52.212768,lng: 0.108756}, '19 October 2017', 'Festival of Ideas - Talk ‘The Colours of Space’ by Helen Schell and Helen Mason - 30 members of the public');
addMarker(map, 'Swavesey Village College, Swavesey', {lat: 52.29418,lng: -0.008292}, '20 October 2017', 'Primary Teachers STEM Meeting - Helen Mason gave talk on ESERO resources, leads workshop on ‘Exoplanets’ and runs SunSpaceArt display - 70 teachers for talk and 30 for each workshop');
addMarker(map, 'British Antarctic Survey , Cambridge', {lat: 52.212802,lng: 0.079903}, '1 November 2017', 'STEM meeting - on Polar Explorer Programme, SunSpaceArt display - 30 teachers and stem ambassadors');
addMarker(map, 'Peterborough Astronomical Society, Peterborough', {lat: 52.591203,lng: -0.405545}, '2 November 2017', 'Astronomy Club = Helen Mason gives talk to 50 amature astronomers');
addMarker(map, 'Sheffield Institute of Physics, Sheffield', {lat: 53.380881,lng: -1.486223}, '12 December 2017', 'Helen Mason gave public lecture - Institute of Physics web video ');
addMarker(map, 'Association of Science Educators, Liverpool', {lat: 53.406449,lng: -2.975511}, '5 January 2018', 'Association of Science Educators (5/6 January 2018) Pop-up-Primary display table and SunSpaceArt workshop for primary teachers – Helen Schell and Helen Mason');
addMarker(map, 'Long Eaton School, Derbyshire', {lat: 52.891899,lng: -1.281643}, '24 January 2018', 'Stargazing Live, 150 students, Key Stage 2 - including Helen Mason talk to primary schools and GCSE/A-level students (100 students, Key Stage 4/5), public lecture to 150 families');
addMarker(map, 'SEERIH, University of Manchester, Manchester', {lat: 53.46668,lng: -2.233581}, '30 January 2018', 'Science and Engineering Education Research and Innovation Hub (SEERIH), Through the Science Window, SunSpaceArt CPD for Primary School Teachers, Helen Schell, Helen Mason, Sam Illingworth (poet) - 20 teachers');
addMarker(map, 'AWISE, Lucy Cavendish College, Cambridge', {lat: 52.210766,lng: 0.110256}, '6 February 2018', 'Association for Women in Science and Engineering (AWISE) – Keynote Address by Helen Mason ‘My Life in the Sun’ - 30 female scientists');
addMarker(map, 'Oxford Road Community School, Reading', {lat: 51.455698,lng: -0.986739}, '8 February 2018', 'ORSAnauts, Helen Mason – Sci/Art workshop on ‘Antarctica’ - 20 students, Key Stage 2, 1 teacher', 'https://www.sunspaceart.org/school-workshops/polar-explorers/');
addMarker(map, 'Maesglas Primary School, Wales', {lat: 51.566928,lng: -3.010834}, '14 February 2018', 'Emma Wride (AstroCymru) and Sarah Bridgland - 45 students, Key Stage 2, Year 6 and 3 teachers ');
addMarker(map, 'The Derby High School of England, Stockport', {lat: 53.582687,lng: -2.305341}, '14 February 2018', 'SunSpaceArt Workshop with 30 students, Key Stage 2', 'https://www.sunspaceart.org/school-workshops/solar-satellite-booklets-in-stockport/');
addMarker(map, 'Falinge High School, Stockport', {lat: 53.624285,lng: -2.167746}, '14 February 2018', 'SunSpaceArt Workshop with 30 students, Key Stage 2', 'https://www.sunspaceart.org/school-workshops/solar-satellite-booklets-in-stockport/');
addMarker(map, 'St Ambrose Barlow RC High School, Stockport', {lat: 53.519839,lng: -2.361311}, '15 February 2018', 'SunSpaceArt Workshop with 30 students, Key Stage 2', 'https://www.sunspaceart.org/school-workshops/solar-satellite-booklets-in-stockport/');
addMarker(map, 'Ambraham Moss , Stockport', {lat: 53.51163,lng: -2.23606}, '15 February 2018', 'SunSpaceArt Workshop with 30 students, Key Stage 2', 'https://www.sunspaceart.org/school-workshops/solar-satellite-booklets-in-stockport/');
addMarker(map, 'Connaught House School, London', {lat: 51.513892,lng: -0.162976}, '20 February 2018', 'SunSpaceArt workshop with Geraldine Cox, Dagny Yousuf, Krishna Mooroogen, Christabel Forbes, Helen Mason - 60 students, Key Stage 1/2, 3 teachers', 'https://www.sunspaceart.org/school-workshops/creative-printing-at-connaught-house-school/');
addMarker(map, 'Cambridge Physics Centre, Cambridge', {lat: 52.208796,lng: 0.092901}, '22 February 2018', 'Helen Mason gives a talk to 100 sixth form students, Key Stage 4/5 and 15 teachers');
addMarker(map, 'St Ambrose Barlow High School, Salford, Manchester', {lat: 53.52043,lng: -2.358387}, '26 February 2018', '‘Smart Materials’ SunSpaceArt workshop (26/26 February 2018), 4 secondary schools, Helen Schell, Deborah Davidson, Helen Masonwith 120 students, Key Stage 3 and 8 teachers', 'https://www.sunspaceart.org/school-workshops/smart-materials-moon-village-design/');
addMarker(map, 'The Derby High School, Bury, Manchester', {lat: 53.582716,lng: -2.305341}, '26 February 2018', '‘Smart Materials’ SunSpaceArt workshop (26/26 February 2018), 4 secondary schools, Helen Schell, Deborah Davidson, Helen Masonwith 120 students, Key Stage 3 and 8 teachers', 'https://www.sunspaceart.org/school-workshops/smart-materials-moon-village-design/');
addMarker(map, 'Falinge Park High School, Rochdale, Manchester', {lat: 53.624376,lng: -2.169304}, '26 February 2018', '‘Smart Materials’ SunSpaceArt workshop (26/26 February 2018), 4 secondary schools, Helen Schell, Deborah Davidson, Helen Masonwith 120 students, Key Stage 3 and 8 teachers', 'https://www.sunspaceart.org/school-workshops/smart-materials-moon-village-design/');
addMarker(map, 'Abraham Moss Community School, Crumpsall, Manchester', {lat: 53.511629,lng: -2.236051}, '26 February 2018', '‘Smart Materials’ SunSpaceArt workshop (26/26 February 2018), 4 secondary schools, Helen Schell, Deborah Davidson, Helen Masonwith 120 students, Key Stage 3 and 8 teachers', 'https://www.sunspaceart.org/school-workshops/smart-materials-moon-village-design/');
addMarker(map, 'Burnham grammar School, Burnham', {lat: 51.532456,lng: -0.653622}, '1 March 2018', 'Helen Mason – Gold Crest mentor - gives talk to GCSE/6th formers - 40 students, Key Stage 4 and 3 teachers');
addMarker(map, 'Wyton-on-the-Hill primary school, Huntingdon', {lat: 52.344079,lng: -0.112126}, '5 March 2018', 'Geraldine Cox, Dagny Yousef, Helen Mason - 40 students, Key Stage 2, Year s 5/6 and 5 teachers', 'https://www.sunspaceart.org/school-workshops/the-vibrating-sun-hidden-patterns/');
addMarker(map, 'AWISE, Queen\'s College, Cambridge', {lat: 52.202136,lng: 0.113979}, '6 March 2018', 'Helen Mason gives talk at the Cambridge Women in Physics dinner to 50 female university students');
addMarker(map, 'Caedmon College, Whitby, North Yorkshire', {lat: 54.482008,lng: -0.62381}, '6 March 2018', '‘Space fashion for the Future\' (6-9 March 2018) Heather MacRae, Helen Schell in partnership with Burberry (Ideas Foundation). Four schools - with 6 teachers, 200 students from different schools, Key Stage 3', 'https://www.sunspaceart.org/school-workshops/burberry-women-pioneers/');
addMarker(map, 'Eskdale School, Whitby, North Yorkshire', {lat: 54.471178,lng: -0.605458}, '7 March 2018', '‘Space fashion for the Future\' (6-9 March 2018) Heather MacRae, Helen Schell in partnership with Burberry (Ideas Foundation). Four schools - with 6 teachers, 200 students from different schools, Key Stage 3', 'https://www.sunspaceart.org/school-workshops/burberry-women-pioneers/');
addMarker(map, 'Graham School, Scarborough, North Yorkshire', {lat: 54.279434,lng: -0.441033}, '8 March 2018', '‘Space fashion for the Future\' (6-9 March 2018) Heather MacRae, Helen Schell in partnership with Burberry (Ideas Foundation). Four schools - with 6 teachers, 200 students from different schools, Key Stage 3', 'https://www.sunspaceart.org/school-workshops/burberry-women-pioneers/');
addMarker(map, 'Gearge Pindar School, Scarborough, North Yorkshire', {lat: 54.238492,lng: -0.394894}, '9 March 2018', '‘Space fashion for the Future\' (6-9 March 2018) Heather MacRae, Helen Schell in partnership with Burberry (Ideas Foundation). Four schools - with 6 teachers, 200 students from different schools, Key Stage 3', 'https://www.sunspaceart.org/school-workshops/burberry-women-pioneers/');
addMarker(map, 'Warboys Primary School, Peterborough', {lat: 52.406556,lng: -0.08366}, '12 March 2018', 'Helen Mason kicked off ‘Space Week’ by giving a talk to  80 students, Key Stage 2 and 10 teachers');
addMarker(map, 'Tremains Primary School, Wales', {lat: 51.508513,lng: -3.552018}, '12 March 2018', 'SunSpaceArt wokshop with Emma Wride (AstroCymru) and Sarah Bridgland with 40 students, Key Stage 2 and 3 teachers', 'https://www.sunspaceart.org/school-workshops/space-go-in-wales/');
addMarker(map, 'Litchard Primary School, Wales', {lat: 51.523639,lng: -3.579582}, '13 March 2018', 'SunSpaceArt wokshop with Emma Wride (AstroCymru) and Sarah Bridgland with 40 students, Key Stage 2 and 3 teachers', 'https://www.sunspaceart.org/school-workshops/space-go-in-wales/');
addMarker(map, 'Coychurch Primary School, Wales', {lat: 51.507848,lng: -3.52688}, '15 March 2018', 'SunSpaceArt wokshop with Emma Wride (AstroCymru) and Sarah Bridgland with 40 students, Key Stage 2 and 4 teachers', 'https://www.sunspaceart.org/school-workshops/space-go-in-wales/');
addMarker(map, 'Vange Primary School, Basildon, Essex', {lat: 51.554808,lng: 0.472725}, '14 March 2018', 'Helen Mason (and John Dudeney) give talks with Heather MacRae, Polar Ambassador to 50 students and 3 teachers');
addMarker(map, 'Temple Sutton Primary School, Southend, Essex', {lat: 51.552907,lng: 0.727263}, '14 March 2018', 'Helen Mason (and John Dudeney) give talks with Heather MacRae, Polar Ambassador to 50 students and 3 teachers');
addMarker(map, 'Reepham Secondary School, Norfolk', {lat: 52.758242,lng: 1.105824}, '19 March 2018', 'Helen Mason – talk, ‘Stargazing Live’ - 80 students, Key Stage 3/4, 6 teachers and families ');
addMarker(map, 'Royal Observatory Greenwich, London', {lat: 51.476873,lng: -0.0007}, '20 March 2018', 'Helen Mason gives ‘Think Space’ talk - 40 Key Stage 4/public');
addMarker(map, 'SouthRise Primary School, Greenwich', {lat: 51.486331,lng: 0.08223}, '21 March 2018', 'Space Day, Helen Mason and Clare Dudeney, Christabel Forbes and Emily Morey - 90 students, Key Stage 2, Year 6 and 5 teachers', 'https://www.sunspaceart.org/school-workshops/pop-up-space-in-greenwich/');
addMarker(map, 'Sir William Borlase Grammar School, Maidenhead', {lat: 51.570276,lng: -0.782253}, '22 March 2018', 'Helen Mason – talk GCSE/6th formers - 40 students, Key Stage 4/5 and 3 teachers');
addMarker(map, 'Rutherford Appleton Laboratory (RAL), Oxon', {lat: 51.574106,lng: -1.311282}, '27 March 2018', 'Rutherford Appleton Laboratory (RAL) ‘SunSpaceArt’ - Schools workshop with Helen Schell, Geraldine Cox, Helen Mason and Alessandra Giunta (RAL Space) - 70 students, Key Stage 2, 6 teachers', 'https://www.sunspaceart.org/school-workshops/solar-satellite-booklets-at-ral/');
addMarker(map, 'Caldecott Primary School, Abingdon, Oxon', {lat: 51.664652,lng: -1.294142}, '27 March 2018', 'Rutherford Appleton Laboratory (RAL) ‘SunSpaceArt’ - Schools workshop with Helen Schell, Geraldine Cox, Helen Mason and Alessandra Giunta (RAL Space) - 70 students, Key Stage 2, 6 teachers', 'https://www.sunspaceart.org/school-workshops/solar-satellite-booklets-at-ral/');
addMarker(map, 'Gorsington Primary School, Oxon', {lat: 51.718159,lng: -1.160193}, '27 March 2018', 'Rutherford Appleton Laboratory (RAL) ‘SunSpaceArt’ - Schools workshop with Helen Schell, Geraldine Cox, Helen Mason and Alessandra Giunta (RAL Space) - 70 students, Key Stage 2, 6 teachers', 'https://www.sunspaceart.org/school-workshops/solar-satellite-booklets-at-ral/');
addMarker(map, 'South Stoke Primary School, Wallingford, Oxon', {lat: 51.547785,lng: -1.137443}, '27 March 2018', 'Rutherford Appleton Laboratory (RAL) ‘SunSpaceArt’ - Schools workshop with Helen Schell, Geraldine Cox, Helen Mason and Alessandra Giunta (RAL Space) - 70 students, Key Stage 2, 6 teachers', 'https://www.sunspaceart.org/school-workshops/solar-satellite-booklets-at-ral/');
addMarker(map, 'The Ilsleys Primary School, Newbury, Oxon', {lat: 51.52434,lng: -1.289908}, '27 March 2018', 'Rutherford Appleton Laboratory (RAL) ‘SunSpaceArt’ - Schools workshop with Helen Schell, Geraldine Cox, Helen Mason and Alessandra Giunta (RAL Space) - 70 students, Key Stage 2, 6 teachers', 'https://www.sunspaceart.org/school-workshops/solar-satellite-booklets-at-ral/');
addMarker(map, 'Rutherford Appleton Laboratory, Oxon', {lat: 51.574106,lng: -1.311382}, '27 March 2018', 'Rutherford Appleton Laboratory (RAL) ‘SunSpaceArt’ - Schools workshop with Helen Schell, Geraldine Cox, Helen Mason and Alessandra Giunta (RAL Space) - 70 students, Key Stage 2, 6 teachers');
addMarker(map, 'National Astronomy Meeting (NAM)/European Week of Astronomy and Space Science (EWASS) 2018, Liverpool', {lat: 53.406449,lng: -2.975597}, '3 April 2018', '(3-5 April 2018) Helen Mason organised ‘Space/Art’ session, she was awarded the RAS Annie Maunder Medal and Helen Schell was an invited speaker - 50 communicators and educators');
addMarker(map, 'Cambridge Pub, Cambridge', {lat: 52.21011,lng: 0.101225}, '16 May 2018', 'Pint of Science and Creative Reactions Sun/Art, Helen Mason worked with artist, Maria Merridan - 40 public and artists');
addMarker(map, 'Institute of Physics , London', {lat: 51.532288,lng: -0.120537}, '17 May 2018', 'Institute of Physics – round table discussion on ‘Girls and A-level Physics’ - with 50 IoP members');
addMarker(map, 'Icknield primary School, Cambridgeshire', {lat: 51.909122,lng: -0.433624}, '23 May 2018', 'SunSpaceArt workshops, Clare Dudeney, Christabel Forbes, Helen Mason - Key Stage 1 (30 students), Key Stage 2 (30 students) and 3 teachers', 'https://www.sunspaceart.org/school-workshops/the-colours-of-space-at-icknield/');
addMarker(map, 'Ely Cathedral, Ely', {lat: 52.398873,lng: 0.26367}, '30 May 2018', '‘Pop-up Science event with 50 families');
addMarker(map, 'Cambridge Park, Cambridge', {lat: 52.21011,lng: 0.101125}, '2 June 2018', 'SoapBox Science');
addMarker(map, 'Goddard Space Flight Center, Washington DC', {lat: 38.99495,lng: -76.852323}, '14 June 2018', 'GSFC – seminar on SunSpaceArt and meeting with NASA STE(A)M Innovation Centre - with 30 scientists and artists');
addMarker(map, 'Gascoigne Primary School, London', {lat: 51.532892,lng: 0.079488}, '19 June 2018', 'Great Science Share, Gascoigne Primary School and several other schools (Helen Mason and John Dudeney, polar scientist) - 200 students, 20 teachers, Key Stage 2');
addMarker(map, 'Broadwater School, Surrey', {lat: 51.201274,lng: -0.594085}, '26 June 2018', 'Get Space, Broadwater School and many other schools, Helen Mason Plenary talk - 100 students, 10 teachers, Key Stage 2 - SunSpaceArt workshops, Helen Schell and Helen Mason - 30 students and 3 teachers', 'https://www.sunspaceart.org/school-workshops/get-space-v/');
addMarker(map, 'Durham University, Durham', {lat: 54.7648,lng: -1.578181}, '28 June 2018', 'Ogden Trust Science/Art event - Helen Mason and Helen Schell gave talks - with 40 artists');
addMarker(map, 'Northern Saints Primary School, Sunderland', {lat: 54.922778,lng: -1.429854}, '29 June 2018', 'SunSpaceArt workshop, Helen Schell, Helen Mason - with 60 students, 3 teachers, Key Stage 2', 'https://www.sunspaceart.org/school-workshops/the-sun-our-star-in-sunderand/');
addMarker(map, 'Christ Church Primary School, London', {lat: 51.531012,lng: -0.144053}, '12 July 2018', 'Polar Science /Art workshop led by Clare Dudeney, with Christabel Forbes, Helen Mason and poet, Mario Petrucci - 60 students, Year  3 and 4, 3 teachers', 'https://www.sunspaceart.org/school-workshops/watercolour-paintings-of-antarctica/');
addMarker(map, 'Arbury Community Center, Cambridge', {lat: 52.226184,lng: 0.128971}, '13 July 2018', 'Home Educators group – SunSpaceArt workshop - 20 students, 10 parents');
addMarker(map, 'University of Leicester, Leicester', {lat: 52.622298,lng: -1.124419}, '3 September 2018', 'John Coxon/MIST Outreach, panel, Helen Mason - 30 science communicators');
addMarker(map, 'Westminster Reference Library, London', {lat: 51.509671,lng: -0.129814}, '4 September 2018', 'Helen Mason gives talk to 50 members of the public');
addMarker(map, 'Northern Saints Primary School, Sunderland', {lat: 54.922784,lng: -1.429854}, '18 September 2018', '‘Sun and Moon’ workshop-  Helen Schell and Helen Mason - 60 students and 3 teachers, Year  5', 'https://www.sunspaceart.org/school-workshops/sun-and-moon-satellite-booklets-in-sunderland/');
addMarker(map, 'Science Museum, London', {lat: 51.4978,lng: -0.1745}, '5 October 2018', 'RAS – space week event, Science Museum\'s exhibition \'The Sun: Living With Our Star\' -  Helen Mason on moderated panel discussion, ‘8 min’ dance - 80 members of the public');
addMarker(map, 'SpaceCamps UK, Ushaw College, Durham', {lat: 54.788419,lng: -1.661102}, '10 October 2018', 'Space Camp UK – Shine Trust, Stehen Hawking Foundation – SunSpaceArt CPD, Helen Schell runs training session for 30 teachers', 'https://www.sunspaceart.org/school-workshops/sunspaceart-and-space-camp-uk/');
addMarker(map, 'Blanche Nevile Primary School, London', {lat: 51.578995,lng: -0.154975}, '12 October 2018', 'SEN, school for deaf students - with 40 students, ages 8-11, 4 teachers - Dagny Yousuf, Christabel Forbes, Geraldine Cox, Helen Mason, Krishna Mooroogen');
addMarker(map, 'Royal Observatory Greenwich, London', {lat: 51.476873,lng: -0.0008}, '15 October 2018', 'Flamstead Astro Soc, Royal Museums Greenwich, Helen Mason gives talk to 80 amateur Astronomers');
addMarker(map, 'Vane Gallery, Newcastle', {lat: 54.973665,lng: -1.611303}, '16 October 2018', '‘Spectrum’, World Space Week – led by Helen Schell, Helen Mason - with 40 scientists and artists');
addMarker(map, 'Llanyrafon Primary School, Wales', {lat: 51.648321,lng: -3.0068404}, '23 October 2018', 'Emma Wride and Sarah Bridgland run workshop - Year  5 – 53 students and 4 teachers', 'https://www.sunspaceart.org/school-workshops/space-go-in-wales/');
addMarker(map, 'New College, Swindon', {lat: 51.557411,lng: -1.758579}, '23 October 2018', 'Helen Mason gives two public talks - 30 students Key Stage 4, 50 public');
addMarker(map, 'Nythe Primary School , Swindon', {lat: 51.565495,lng: -1.740251}, '24 October 2018', 'SunSpaceArt workshop with Clare Dudeney, Christabel Forbes, Helen Mason, Neville - 2 classes of 30 students and 4 teachers, Year  5', 'https://www.sunspaceart.org/school-workshops/marbling-the-solar-system-in-swindon/');
addMarker(map, 'John Innes Centre, Norwich', {lat: 52.622291,lng: 1.221381}, '26 October 2018', 'TSN, Breckland Astron, Norwich Science Festival, Helen Mason gives talk to 25 amateur Astronomers');
addMarker(map, 'Science Museum, London', {lat: 51.4978,lng: -0.1746}, '3 November 2018', 'Family Sun Festival, SunSpaceArt workshops with 90 family members - Helen Schell, Helen Mason, Clare Dudeney', 'https://www.sunspaceart.org/school-workshops/science-museum-the-sun-family-festival/');
addMarker(map, 'Science Museum, London', {lat: 51.4978,lng: -0.1747}, '4 November 2018', 'Family Sun Festival, SunSpaceArt workshops with 140 family members on 04 November 2020 - Helen Schell, Helen Mason, Clare Dudeney', 'https://www.sunspaceart.org/school-workshops/science-museum-the-sun-family-festival/');
addMarker(map, 'Canonbury Primary School, London', {lat: 51.544936,lng: -0.101158}, '5 November 2018', 'SunSpaceArt workshop with Geraldine Cox, Dagny Yousuf, Christabel Forbes, Clare Dudeney, Helen Mason, Mario Petrucci - 30 students x 2 classes and 5 teachers, Year  5/6', 'https://www.sunspaceart.org/school-workshops/sun-and-space-inspired-mobiles/');
addMarker(map, 'Glassllwych Primary School, Wales', {lat: 51.58218,lng: -3.028048}, '8 November 2018', 'SunSpaceArt Workshop with Emma Wride and Sarah Bridgland - Year 5 – 31 students and 2 teachers', 'https://www.sunspaceart.org/school-workshops/pop-up-sun-in-wales/');
addMarker(map, 'Ysgol Pontrobert, Wales', {lat: 52.703119,lng: -3.323646}, '19 November 2018', 'SunSpaceArt Workshop with Emma Wride and Sarah Bridgland - Years 1-6, 31 students and 3 teachers', 'https://www.sunspaceart.org/school-workshops/pop-up-sun-in-ysgol-pontrobert/');
addMarker(map, 'Science Museum, London', {lat: 51.4978,lng: -0.1748}, '28 November 2018', '‘The Sun’ Lates with Helen Schell, Dagny Yousuf, Clare Dudeney, Christabel Forbes, Krishna Mooroogen - 150 adults – public and teachers', 'https://www.sunspaceart.org/school-workshops/sun-lates-at-the-science-museum/');
addMarker(map, 'Rutherford Appleton Laboratory, Didcot', {lat: 51.573814,lng: -1.314559}, '6 December 2018', '14th Appleton Space Conference - Helen Mason gave a talk');
addMarker(map, 'Science Museum, London', {lat: 51.4978,lng: -0.1749}, '8 December 2018', 'Science Museum - \'Night Owls\', Spcial Educational Needs, SEN, young adults - Helen Schell, Christabel Forbes, helen Mason - with 30 young people.', 'https://www.sunspaceart.org/school-workshops/night-owls-at-the-science-museum/');
addMarker(map, 'Maths/Art Workshops, DAMTP, Cambridge', {lat: 52.210117,lng: 0.101215}, '10 December 2018', 'Meeting to discuss Maths/Art projects');
addMarker(map, 'Association of Science Educators, Birmingham', {lat: 52.45113,lng: -1.931708}, '11 January 2019', 'Association of Science Educators, ASE (SunSpaceArt CPD workshop and Pop-up science display) Helen Mason, Helen Schell with 50 teachers');
addMarker(map, 'Torquay Girls Secondary School, Devon', {lat: 50.475975,lng: -3.553408}, '15 January 2019', 'Helen Mason gave a talk and ran a workshop with five classes of 30 Year  10 students and 5 teachers');
addMarker(map, 'University College London, London', {lat: 51.524579,lng: -0.134029}, '21 January 2019', 'Helen Mason talk to 30 undergraduate engineers');
addMarker(map, 'Highway Primary School, Orpington, Kent', {lat: 51.359934,lng: 0.111087}, '22 January 2019', 'Helen Schell and Helen Mason run school workshop with 32 Year  5 students and 3 teachers');
addMarker(map, 'Institute of Physics , London', {lat: 51.532288,lng: -0.120637}, '5 February 2019', 'Institute of Physics students’s event, Helen Mason attending');
addMarker(map, 'University of Bath, Bath', {lat: 51.378035,lng: -2.327}, '6 February 2019', ' Helen Mason gives a talk to 30 undergraduate students');
addMarker(map, 'Somali Community Centre, Leicester', {lat: 52.639215,lng: -1.121782}, '9 February 2019', 'Space Science Celebration with 20 Somali Youths, SOCOPA, STFC Wonder Match');
addMarker(map, 'Rugby School, Rugby', {lat: 52.370342,lng: -1.261566}, '11 February 2019', ' Helen Mason gives evening lecture to 40 students, Key Stage 4/5 and 4 teachers');
addMarker(map, 'Saint Peter’s Methodist Primary School, Canterbury, Kent', {lat: 51.279983,lng: 1.077065}, '15 February 2019', 'SpaceFund Jo –  Helen Mason, Christabel Forbes, Sehar Sheikh run workshop with 30 students, Key Stage 2, and 3 teachers');
addMarker(map, 'Bryn Bach primary School, Wales', {lat: 51.786387,lng: -3.262116}, '19 February 2019', 'Emma Wride and Sarah Bridgland run workshop with 30 students, Key Stage 2, Year 6, and 2 teachers', 'https://www.sunspaceart.org/school-workshops/pop-up-sun-in-wales/');
addMarker(map, 'Fochriw Primary School, Merythr Tydfil, Wales', {lat: 51.742677,lng: -3.29568}, '21 February 2019', 'Emma Wride and Sarah Bridgland run workshop with 30 students, Key Stage 2, Year s5-6, and 2 teachers', 'https://www.sunspaceart.org/school-workshops/pop-up-sun-in-wales/');
addMarker(map, 'St Michaels Primary School, Surrey', {lat: 51.104889,lng: 0.139303}, '26 February 2019', 'Helen Schell and Helen Mason run workshop with 30 students, Key Stage 2, and 2 teachers');
addMarker(map, 'Science Museum, London', {lat: 51.4978,lng: -0.175}, '2 March 2019', 'Helen Schell, Helen Mason, Clare Dudeney, Christabel Forbes, Juie Shetye (solar scientist) and Minal Patel run family workshop on the Sun with 200 people ');
addMarker(map, 'Science Museum, London', {lat: 51.4978,lng: -0.1751}, '3 March 2019', 'Helen Schell, Helen Mason, Clare Dudeney, Christabel Forbes, Juie Shetye (solar scientist) and Minal Patel run family workshop on the Sun with 300 people');
addMarker(map, 'Vittoria Primary School, Islington , London', {lat: 51.535465,lng: -0.112579}, '4 March 2019', 'Our Place in the Universe - Helen Mason, Christabel Forbes and Clare Dudeney run workshop with 30 students and 2 teachers - Year 5 (Key Stage 2)', 'http://www.sunspaceart.org/school-workshops/our-place-in-the-universe-vittoria-ps/');
addMarker(map, 'St Ambrose Barlow RC High School, Manchester', {lat: 53.520434,lng: -2.358387}, '6 March 2019', 'Helen Schell and Helen Mason give workshop with 46 students, Key Stage 3, and 2 teachers');
addMarker(map, 'Physics in Action, Emmanuel Centre, Talk to Sixth formers, London', {lat: 51.496139,lng: -0.129032}, '8 March 2019', 'Helen Mason gives talk to 200 female A-level students and 20 teachers from 15 schools');
addMarker(map, 'Clytha Primary School, Newport, Wales', {lat: 51.584867,lng: -3.011424}, '8 March 2019', 'Emma Wride and Sarah Bridgland give workshop with 30 students, Key Stage 2, Year 6, and 2 teachers', 'https://www.sunspaceart.org/school-workshops/pop-up-sun-in-wales/');
addMarker(map, 'Astronomy Society, Kidderminster', {lat: 52.383217,lng: -2.23351}, '13 March 2019', 'Helen Mason gives Astro club talk with 40 members of the public');
addMarker(map, 'King Charles I School, Kidderminster', {lat: 52.383848,lng: -2.234276}, '14 March 2019', 'Helen Mason gives talk to 30 students, Key Stage 3, 10 students Key Stage 4/5 and 5 teachers');
addMarker(map, 'Maesglas Primary School, Newport, Wales', {lat: 51.566915,lng: -3.010834}, '14 March 2019', 'Emma Wride and Sarah Bridgland give school workshop to 45 students. Key Stage 2, Year 6 and 2 teachers', 'https://www.sunspaceart.org/school-workshops/pop-up-sun-in-wales/');
addMarker(map, 'Manor School, Brent , London', {lat: 51.537052,lng: -0.221215}, '15 March 2019', 'Helen Mason, Christabel Forbes and Sehar Sheikh give a school workship to 25 students with Special Educational Needs and 3 teachers', 'https://www.sunspaceart.org/school-workshops/journeys-through-space/');
addMarker(map, 'Sandfield Close School, Leicester', {lat: 52.668077,lng: -1.096999}, '19 March 2019', 'Helen Schell, Helen Mason and Katrina Porteous (poet) give workshop with 30 students, Key Stage 2, and 5 teachers');
addMarker(map, 'DAMTP, University of Cambridge, Cambridge', {lat: 52.21011,lng: 0.101004}, '23 March 2019', 'Helen Mason takes part in CMS/Maths Faculty Open Day with 100 members of the public');
addMarker(map, 'St Andrew’s Primary School, Hove', {lat: 50.830605,lng: -0.174918}, '27 March 2019', 'Helen Mason and John Dudeney give workshop on Polar Science with  30 students and 2 teachers, Key Stage 1');
addMarker(map, 'West Hove Infant School, Hove', {lat: 50.834892,lng: -0.190273}, '27 March 2019', 'Helen Mason and John Dudeney give workshop on Polar Science with  30 students and 2 teachers, Key Stage 2');
addMarker(map, 'Allensbank Primary School, Wales', {lat: 51.502256,lng: -3.185988}, '8 April 2019', 'Emma Wride (AstroCymru) and Sarah Bridgland give school workshop with 34 students, Key Stage 2, Year 5-6, and 2 teachers', 'https://www.sunspaceart.org/school-workshops/pop-up-sun-in-wales/');
addMarker(map, 'Astronomy Society, Cardiff, Cardiff', {lat: 51.488931,lng: -3.179774}, '16 May 2019', 'Helen Mason gives talk to Astronomy club with 70 members of the public');
addMarker(map, 'Ely Cathedral, Ely', {lat: 52.398873,lng: 0.26357}, '20 May 2019', 'Moon exhibition and events (20-30 May 2019) - attracting 21,200 visitors,  Helen Schell and Helen Mason give public workshops, Helen Schell\'s artwork is on display');
addMarker(map, 'Ely Cathedral, Ely', {lat: 52.398873,lng: 0.26347}, '20 May 2019', 'Helen Schell and Helen Mason give school workshops to 60 students, Key Stage 2, and 4 teachers from Ten Mile Bank Primary and Hilgay Primary');
addMarker(map, 'Ely Cathedral, Ely', {lat: 52.398873,lng: 0.26337}, '21 May 2019', 'Helen Schell and Helen Mason give school workshops to 30 students, Key Stage 3, 20 students, Key Stage 2 and 6 teachers from Soham Village College and Foxton Primary');
addMarker(map, 'Science Museum, London', {lat: 51.4978,lng: -0.1752}, '25 May 2019', 'Helen Schell, Sehar Sheikh and Olwen Hill (teacher) give family workshops on the Moon to 66 members of the public');
addMarker(map, 'Ely Cathedral, Ely', {lat: 52.398873,lng: 0.26327}, '29 May 2019', 'Helen Mason runs family drop in workshop with 80 families');
addMarker(map, 'Torriano School, Camden, London', {lat: 51.549707,lng: -0.132662}, '3 June 2020', 'Helen Schell, Helen Mason and Alice White run school workshop with 60 students, Key Stage 2, Year 5, and 5 teachers');
addMarker(map, 'Ysgol Gyun Y Strade, Wales', {lat: 51.686698,lng: -4.181412}, '5 June 2019', 'Emma Wride and Sarah Bridgland run school workshops for GSS involving 54 students, Key Stage 2, Year s 5/6 and 6 teachers from five schools - Ysgol Gyun Y Strade (host), Ysgol Trimsaran, Ysgol Mynydd y Garreg, Ysgol Gymraeg y Ffwrnes and Ysgol Gymraeg Gwenllian');
addMarker(map, 'Primary Science Education Conference, Edinburgh', {lat: 55.946191,lng: -3.209815}, '7 June 2019', 'Primary Science Education Conference / Primary Science Teachers Trust. Helen Mason gives training session for 30 teachers ');
addMarker(map, 'Ysgol Glan Y Mor, Wales', {lat: 52.881921,lng: -4.422538}, '10 June 2019', 'Emma Wride and Sarah Bridgland give school workshops to 110 students, Key Stage 2, Years 5/6, and 6 teachers');
addMarker(map, 'National Botanic Garden of Wales, Wales', {lat: 51.83994,lng: -4.151486}, '18 June 2019', 'Great Science Share - Emma Wride, Helen Mason and John Dudeney give several talks to 283 students, Key Stage 2, 26 teachers and 39 home educators');
addMarker(map, 'Purfleet Primary School, Purfleet', {lat: 51.485444,lng: 0.234006}, '20 June 2019', 'Helen Mason, John Dudeney, Clare Dudeney and Kulvinder Johal (PSTT) run school workshop on Polar Explorers with 90 students, Key Stage 2, Year 5 and 6 teachers');
addMarker(map, 'Torriano Primary School, London', {lat: 51.549714,lng: -0.132662}, '21 June 2019', 'Helen Mason visits ‘Sun exhibition’ for families');
addMarker(map, 'St Ambrose Barlow RC High School, Stockport', {lat: 53.519839,lng: -2.361411}, '25 June 2019', 'Helen Schell runs a second workhop with the school involving 30students, Key Stage 3 and 3 teachers');
addMarker(map, 'Durham University, Durham', {lat: 54.7648,lng: -1.578281}, '27 June 2019', 'Helen Schell and Helen Mason take part in an event on Changing Cosmic Perceptions with 40 Artists and Scientists');
addMarker(map, 'Lancaster University, Lancaster', {lat: 54.010407,lng: -2.787718}, '2 July 2019', 'Helen Mason and Helen Schell run a workshop on \'Engaging the Public and Schools with Science through the Solar System\' at the National Astronomy Meeting 2019. With 60 Researchers and Science communicators');
addMarker(map, 'Institute of Physics, London', {lat: 51.532288,lng: -0.120737}, '20 July 2019', 'Helen Schell gives a family workshop on a \'Moon Adventure\' for 75 people');
addMarker(map, 'Science Museum, London', {lat: 51.4978,lng: -0.1753}, '21 July 2019', 'Helen Schell, Helen Mason, Alice White and Olwen Hill (teacher) run family workshops on the ‘Moon’ with 140 people');
addMarker(map, 'Institute of Physics, London', {lat: 51.532288,lng: -0.120837}, '31 July 2019', 'Helen Schell gives a family workshop on a \'Moon Adventure\' for 200 people');
addMarker(map, 'Manchester Museum of Science and Industry (MOSI), Manchester', {lat: 53.477165,lng: -2.254561}, '17 August 2019', 'Helen Schell, Sehar Sheikh, Prof Robert Walsh, Dr Juie Shetye, Malcom Walsh and Shahbaz Chaudhry run family workshop with 220 people');
addMarker(map, 'Manchester Museum of Science and Industry (MOSI), Manchester', {lat: 53.477165,lng: -2.254661}, '18 August 2019', 'Helen Schell, Sehar Sheikh, Prof Robert Walsh, Dr Juie Shetye, Malcom Walsh and Shahbaz Chaudhry run family workshop with 200 people');
addMarker(map, 'Whitton Community Primary School, Ipswich', {lat: 52.081175,lng: 1.128888}, '2 September 2019', 'Helen Mason held a CPD session with 35 teachers, Key Stage 2');
addMarker(map, 'The University of Central Lancashire, Preston', {lat: 53.763957,lng: -2.709138}, '4 September 2019', 'Helen Mason and Helen Schell participated in the INTERACT event - running two sessions (one with Durham University, ‘Changing Cosmic Perceptions’, one led by Helen Schell on the ‘Moon’). Interacted with about 70 researchers and science communicators. Also had a SunSpaceArt display table.');
addMarker(map, 'RICE University Space Institute, USA', {lat: 29.717236,lng: -95.401799}, '7 September 2019', 'Hellen Schell visited NASA (7-21 Sept 2019), RICE University and the Learning and Performance Institute - meeting 25 scientists and 1 artist');
addMarker(map, 'Ely Cathedral Conference Center, Ely', {lat: 52.39791,lng: 0.263935}, '13 September 2019', 'Helen Mason gives talk at Ely Astronomy Society to 40 amateur astronomers and the general public');
addMarker(map, 'Wymondham College, Norfolk', {lat: 52.544753,lng: 1.057658}, '18 September 2019', 'Helen Mason gives talk to 60 students, Key Stage 4/5 and 5 teachers');
addMarker(map, 'National Solar Observatory, ', {lat: 40.011751,lng: -105.245774}, '30 September 2019', 'Helen Mason talks at the National Solar Observatory (NSO)');
addMarker(map, 'High Altitude Observatory, Boulder', {lat: 40.031172,lng: -105.246044}, '3 October 2019', 'Helen Mason talks at High Altitude Observatory (HAO) ');
addMarker(map, 'Grand County High School, Moab', {lat: 38.565022,lng: -109.545373}, '8 October 2019', 'Helen Mason gives talk at a school in Moab, Utah to 30 students, Key Stage 4/5 and 1 teacher');
addMarker(map, 'The Winter Gardens, Blackpool', {lat: 53.817012,lng: -3.052007}, '15 October 2019', 'The Sun exhibition and workshop with the University of Central Lancashire (UCLAN) for the Blackpool Illuminations (15-18 Oct 2019) - led by Prof Robert Walsh. School workshops led by Helen Schell, Helen Mason, Christabel Forbes Forbes, Sehar Sheikh and Juie Shetye with 220 students, Key Stage 2, Years 5 and 6 and 15 teachers');
addMarker(map, 'AKS Lytham Independent School, Blackpool', {lat: 53.742193,lng: -3.012615}, '15 October 2019', 'The Sun exhibition and workshop with the University of Central Lancashire (UCLAN) for the Blackpool Illuminations (15-18 Oct 2019) - led by Prof Robert Walsh. School workshops led by Helen Schell, Helen Mason, Christabel Forbes Forbes, Sehar Sheikh and Juie Shetye with 220 students, Key Stage 2, Years 5 and 6 and 15 teachers');
addMarker(map, 'Revoe Learning Academy, Blackpool', {lat: 53.807484,lng: -3.04335}, '16 October 2019', 'The Sun exhibition and workshop with the University of Central Lancashire (UCLAN) for the Blackpool Illuminations (15-18 Oct 2019) - led by Prof Robert Walsh. School workshops led by Helen Schell, Helen Mason, Christabel Forbes Forbes, Sehar Sheikh and Juie Shetye with 220 students, Key Stage 2, Years 5 and 6 and 15 teachers');
addMarker(map, 'St Kentigern\'s Primary School, Manchester', {lat: 53.44274,lng: -2.236848}, '17 October 2019', 'The Sun exhibition and workshop with the University of Central Lancashire (UCLAN) for the Blackpool Illuminations (15-18 Oct 2019) - led by Prof Robert Walsh. School workshops led by Helen Schell, Helen Mason, Christabel Forbes Forbes, Sehar Sheikh and Juie Shetye with 220 students, Key Stage 2, Years 5 and 6 and 15 teachers');
addMarker(map, 'Unity Academy Blackpool, Blackpool', {lat: 53.835841,lng: -3.037993}, '18 October 2019', 'The Sun exhibition and workshop with the University of Central Lancashire (UCLAN) for the Blackpool Illuminations (15-18 Oct 2019) - led by Prof Robert Walsh. School workshops led by Helen Schell, Helen Mason, Christabel Forbes Forbes, Sehar Sheikh and Juie Shetye with 220 students, Key Stage 2, Years 5 and 6 and 15 teachers');
addMarker(map, 'Westminster Primary Academy, Blackpool, Blackpool', {lat: 53.829676,lng: -3.047987}, '19 October 2019', 'The Sun exhibition and workshop with the University of Central Lancashire (UCLAN) for the Blackpool Illuminations (15-18 Oct 2019) - led by Prof Robert Walsh. School workshops led by Helen Schell, Helen Mason, Christabel Forbes Forbes, Sehar Sheikh and Juie Shetye with 220 students, Key Stage 2, Years 5 and 6 and 15 teachers');
addMarker(map, 'Exeter Road Community Primary School, Exmouth, Devon', {lat: 50.622333,lng: -3.41128}, '7 November 2019', 'Helen Schell and Helen Mason run school workshop with 90 students, Key Stage 1, 90 students, Key Stage 2 and 12 teachers');
addMarker(map, 'Somali Community Centre, Leicester', {lat: 52.642567,lng: -1.127285}, '23 November 2019', 'Wonder Match (Sarah Langford lead) Science Celebration - Helen Mason led workshop with 30 Somali Youths and 3 teachers');
addMarker(map, 'Ysgol Gynradd Gymraeg, Llyn-Y-Forwyn in Ferndale, Rhondda, Wales', {lat: 51.658681,lng: -3.450206}, '27 November 2019', 'Emma Wride runs workshop with 30 students, Key Stage 2, Year 6 and 2 teachers');
addMarker(map, 'Keir Hardie Primary School, London', {lat: 51.516381,lng: 0.019907}, '3 December 2019', ' Helen Mason, Clare Dudeney and Christabel Forbes run workshop on ‘Journey into Space\' with 60 students, Key Stage 2, and 4 teachers');
addMarker(map, 'Ysgol Gynradd Llandeilo Primary School, Wales', {lat: 51.886529,lng: -3.990139}, '6 December 2019', 'Emma Wride runs workshop with 30 students, Key Stage 2, Year 6 and 2 teachers');
addMarker(map, 'Association of Science Educators, Reading', {lat: 51.440776,lng: -0.94677}, '10 January 2020', 'Association of Science Educators conference - Helen Mason and Helen Schell give SunSpaceArt CPD session and PopUpPrimary workshop');
addMarker(map, 'Somali Community Centre, Leicester', {lat: 52.64258,lng: -1.127307}, '18 January 2020', 'Space Center (visit by Somali Youths) with 30 students and 4 teachers');
addMarker(map, 'BBC - Radio4 - In Our Time, London', {lat: 51.518587,lng: -0.143756}, '23 January 2020', 'Helen Mason joins a panel debate on BBC R4 – ‘In Our Time – Solar Wind’ reaching 3 million members of the public');
addMarker(map, 'University Centre for Astronomy and Astrophysics (IUCAA), Pune, India', {lat: 18.55934,lng: 73.82531}, '7 February 2020', 'Helen Mason gives talk ‘From Sun to Earth’ to 400 students, Key Stage 3/4 and 20 teachers');
addMarker(map, 'Institute of Physics , London', {lat: 51.532288,lng: -0.120937}, '5 February 2020', 'Helen Schell participated in the ‘Art and Science Teaching Project’ led by Exeter University with 15 primary and secondary school teachers and 7 organisers');
addMarker(map, 'Sacred Heart R.C. Primary School, Bolton', {lat: 53.552416,lng: -2.52187}, '2 March 2020', 'Helen Schell and Helen Mason led a CPD session with 7 teachers and 13 trainee teachers');
addMarker(map, 'Great and Little Shelford P.S., Cambridgeshire', {lat: 52.14638,lng: 0.129559}, '9 March 2020', 'Helen Schell and Helen Mason ran SunSpaceArt school workshop');
addMarker(map, 'Sacred Heart R.C. Primary School, Bolton', {lat: 53.552416,lng: -2.52197}, '21 May 2020', 'Helen Schell and Helen Mason led a follow up CPD session with 7 teachers and 13 trainee teachers via zoom');
addMarker(map, 'Marra Scouts Camp, Causey Park Farm, Sunderland ', {lat: 55.25,lng: -1.71327}, '22 May 2020', 'Helen Schell provided online SunSpaceArt activities to 3,000 participants engaged in the Science Technology Engineering and Maths (STEM) North East event at Marra Scouts Camp.');
addMarker(map, 'Online – DASH Astronomy Society, Norfolk', {lat: 52.906787,lng: 1.0906198}, '19 July 2020', 'Helen Mason delivered an online talk on Solar Orbiter for the DASH Astronomy Society, attracting an audience of 60 astronomers and members of the public.	');
addMarker(map, 'Online - SolarSphere Festival, Midlands/Wales/national', {lat: 52.161208,lng: -3.4175187}, '15 August 2020', 'During the online SolarSphere Festival, an educational workshop was conducted by Emma Wride (AstroCymru) , and Helen Mason delivered a talk, the event attracted an audience of 60 members of the public.');
addMarker(map, 'Online – Royal Astronomical Society & Princes Trust, London', {lat: 51.508576,lng: -0.13960806}, '17 August 2020', 'Helen Mason delivered a talk about the Sun to 25 disadvantaged young people through an event organised by the Royal Astronomical Society in collaboration with the Prince\'s Trust.');
addMarker(map, 'Museum of Science and Industry , Manchester', {lat: 53.477284,lng: -2.2550018}, '31 August 2020', 'The Science, Technology, Engineering, and Mathematics (STEM) at the Museum of Science and Industry (MOSI) Spotlight Project, led by Jenifer Lobo from MOSI, featured the participation of Helen Schell and directly engaged 20 schools, reaching hundreds of children.');
addMarker(map, 'Fergussen College, Pune, India', {lat: 18.5228446,lng: 73.836586}, '7 September 2020', 'Helen Mason delivered an online talk about the Sun to a group of 300 university students at Fergussen College.');
addMarker(map, 'Online - schools in the North East, Sunderland', {lat: 54.906101,lng: -1.38113}, '8 October 2020', 'As part of Space Week (4-10 Oct), the Science Technology Engineering and Maths North East (STEM NE) program Helen Schell and Helen Mason hosted online workshops on \'The Sun, our star\' and  \'Make-it–Solar Pop-up Cards\' activity. These sessions engaged 100 children from Key Stage 2 along with five teachers.');
addMarker(map, 'Online - Westminster City Lions Youth Club, London', {lat: 51.51,lng: 0.12}, '27 October 2020', 'Geraldine Cox and Steph Yardley, a solar scientist, led an online \'Drawing the Sun\' session involving four youths aged 13-16 years and two youth leaders, from the Westminster City Lions Youth Club.');
addMarker(map, 'Online - Westminster City Lions Youth Club, London', {lat: 51.51,lng: 0.1199}, '28 October 2020', 'Geraldine Cox and Steph Yardley, a solar scientist, led an online \'Drawing the Sun\' session involving four youths aged 13-16 years and two youth leaders, from the Westminster City Lions Youth Club.');
addMarker(map, 'Online - Elan Valley Dark Skies , Wales', {lat: 52.271923,lng: -3.5655894}, '1 November 2020', 'Emma Wride (AstroCymru)  conducted a SunSpaceArt demonstration, attended by a total of 133 people, with 32 participants on Zoom and an additional 101 viewers on YouTube.');
addMarker(map, 'Ysgol Pen Y Bryn, Wales', {lat: 51.52307,lng: -3.117686}, '9 November 2020', 'Emma Wride (AstroCymru)  conducted a workshop with 28 children in Year 6 (Key Stage 2).');
addMarker(map, 'Mayals Primary School, Swansea', {lat: 51.591474,lng: -4.010028}, '16 November 2020', 'Emma Wride (AstroCymru)  conducted a workshop with 30 children in Year 6 (Key Stage 2).');
addMarker(map, 'Ynyshir, Mid Glamorgan', {lat: 51.622474,lng: -3.4084492}, '23 November 2020', 'Emma Wride (AstroCymru)  conducted a workshop with 56 children in Years 5 and 6 (Key Stage 2).');
addMarker(map, 'Online - St Martin of Porres School , London', {lat: 51.607914,lng: -0.13328249}, '27 November 2020', 'St. Martin of Porres School hosted an online \'Drawing the Sun\' session led by Geraldine Cox and Steph Yardley, a solar scientist. The session involved 26 children from Year 5 (Key Stage 2) and two teachers.');
addMarker(map, 'Online - St Joseph’s School, London', {lat: 51.516189,lng: -0.12187259}, '2 December 2020', 'St. Joseph\'s School hosted an online \'Drawing the Sun\' session led by Geraldine Cox and Steph Yardley, a solar scientist, with 30 Year 5 children, accompanied by one teacher.');
addMarker(map, 'Online - Techniquest, Wales', {lat: 51.462857,lng: -3.166971}, '3 December 2020', 'Techniquest hosted an online Continuing Professional Development (CPD) session led by Emma Wride (AstroCymru) , which was attended by 45 teachers from Key Stage 2.');
addMarker(map, 'Online - St Joseph’s School, London', {lat: 51.516189,lng: -0.12197259}, '4 December 2020', 'St. Joseph\'s School hosted a follow up online \'Drawing the Sun\' session led by Geraldine Cox and Steph Yardley, a solar scientist, with 30 Year 5 children, accompanied by one teacher.');
addMarker(map, 'Online - St Martin of Porres School, London', {lat: 51.607914,lng: -0.13338249}, '11 December 2020', 'St. Martin of Porres School hosted a follow up online \'Drawing the Sun\' session led by Geraldine Cox and Steph Yardley, a solar scientist. The session involved 26 children from Year 5 (Key Stage 2) and two teachers.');
addMarker(map, 'Online - SolarSphere , ', {lat: 51.620046,lng: -0.31774763}, '19 December 2020', 'During the online SolarSphere event, there was a SunSpaceArt demonstration by Emma Wride (AstroCymru)  and a short talk by Helen Mason. The event had a total audience of 123,842, with 45 attendees on Zoom, 326 on YouTube, and an impressive 123,453 listeners on AstroRadio.');
addMarker(map, 'University of Hertfordshire, Hatfield', {lat: 51.76006,lng: -0.25051602}, '7 January 2021', 'At the Association for Science Education (ASE) TeachMeet event, a SunSpaceArt talk was delivered to 50 teachers as part of a Continuing Professional Development (CPD) session.');
addMarker(map, 'University of Leicester, Leicester', {lat: 52.621919,lng: -1.1238104}, '9 January 2021', 'Helen Mason collaborated with Sarah Langford to conduct a training day for Somali youths, which involved 8 young individuals and 3 adults.');
addMarker(map, 'St Martin of Porres Catholic Primary School, London', {lat: 51.607914,lng: -0.13348249}, '13 January 2021', 'St. Martin of Porres Catholic Primary School hosted a SunSpaceArt workshop led by Geraldine Cox and Steph Yardley for 30 Year 6 children in Key Stage 2, with the supervision of one teacher.');
addMarker(map, 'Royal Astronomical Society (RAS), London', {lat: 51.508576,lng: -0.13970806}, '14 January 2021', 'Helen Mason gave a talk for the Royal Astronomical Society (RAS) that was attended by 50 participants.');
addMarker(map, 'Sacred Heart Primary School, Bolton', {lat: 53.552369,lng: -2.5218595}, '2 February 2021', 'At Sacred Heart Primary School, a SunSpaceArt Continuing Professional Development (CPD) session was conducted for 25 trainee teachers.');
addMarker(map, 'Online - Association for Science Education (ASE)  , National', {lat: 51.752896,lng: -0.24288238}, '4 February 2021', 'At the Association for Science Education (ASE) Stargazing event, an online Continuing Professional Development (CPD) session was conducted by Emma Wride (AstroCymru) , with the participation of 75 teachers.');
addMarker(map, 'Cardiff University, Wales', {lat: 51.489066,lng: -3.1798111}, '18 February 2021', 'An online SunSpaceArt demonstration led by Emma Wride (AstroCymru)  had 36 participants on Zoom.');
addMarker(map, 'Festival of tomorrow, Swindon', {lat: 51.390857,lng: -2.1624248}, '19 February 2021', 'At the Swindon Festival of Tomorrow, a talk was given for schools and the public, the team engaged 700 people.');
addMarker(map, 'Shaw CofE Primary School, Wiltshire', {lat: 51.390857,lng: -2.1625248}, '23 February 2021', 'An online school workshop was held at Shaw School in Wiltshire for 30 children in Key Stage 2 (Year 5) with one teacher.');
addMarker(map, 'Online - Sacred Heart Primary School, Bolton', {lat: 53.552369,lng: -2.5219595}, '10 March 2021', 'An online Continuing Professional Development (CPD) session on The Sun was led by Helen Schell and Helen Mason at Sacred Heart Roman Catholic Primary School, in collaboration with the Comino Foundation, involving 25 trainee teachers.');
addMarker(map, 'Online - Sacred Heart Primary School, Bolton', {lat: 53.552369,lng: -2.5220595}, '11 March 2021', 'An online Continuing Professional Development (CPD) session on Mars Village was conducted by Helen Schell and Helen Mason at Sacred Heart Roman Catholic Primary School, in collaboration with the Comino Foundation, with 25 trainee teachers.');
addMarker(map, 'Online – Gurnard Primary School, Isle of White', {lat: 50.761261,lng: -1.3172676}, '12 March 2021', 'Geraldine Cox and Steph Yardley conducted a \'Drawing the Sun\' session for 200 children in Key Stages 1 and 2, along with 10 teachers.');
addMarker(map, 'Online - Sacred Heart Primary School, Bolton', {lat: 53.552369,lng: -2.5221595}, '17 March 2021', 'An online CPD session was led by Clare Dudeney and Helen Mason at Sacred Heart Roman Catholic Primary School, in collaboration with Sustainability First, with the participation of 25 trainee teachers.');
addMarker(map, 'Royal Observatory, Edinburgh', {lat: 55.923201,lng: -3.1878623}, '4 April 2021', 'The Science and Technology Facilities Council (STFC), Royal Observatory Edinburgh (ROE), James Webb Space Telescope (JWST) and Edinburgh Discover Group organised a \'Spring into Spring\'  event featuring SunSpaceArt activities and a workshop led by Helen Schell, reaching 500 families via Facebook.');
addMarker(map, 'Northumbria University, Newcastle', {lat: 54.976762,lng: -1.6074983}, '12 April 2021', 'Helen Mason participated in SolarNet Public Engagement, an online communication training program for European solar scientists led by Northumbria University.');
addMarker(map, 'Risca Community Comprehensive School , Newport', {lat: 51.605734,lng: -3.0701853}, '12 April 2021', 'Emma Wride (AstroCymru) conducted a \'Collages\' workshop for 11-19-year-olds with 10 students, in collaboration with the Princes Trust.');
addMarker(map, 'Online - The Great Science Share for Schools, National', {lat: 53.466853,lng: -2.2364586}, '10 May 2021', 'The Great Science Share for Schools featured \'Space + SunSpaceArt\' materials provided by Geraldine Cox, Steph Yardley, Helen Mason, Emma Wride, and Clare Dudeney (in partnership Sustainability First), led by Lynne Bianchi, reaching hundreds of schools and thousands of children.');
addMarker(map, 'Italian Primary School, SIAL, London', {lat: 51.505886,lng: -0.21175149}, '20 May 2021', 'The Shadow Puppets project, conducted over a whole term at Italian Primary School (SIAL), was led by Christabel Forbes. Sehar Sheikh and Helen Mason joined online on May 20th, involving 30 children and 2 teachers.');
addMarker(map, 'Cowbridge Comprehensive School, Wales', {lat: 51.463848,lng: -3.4364244}, '28 May 2021', 'Emma Wride (AstroCymru) conducted a \'collages\' workshop for 11-19-year-olds with 10 students and 2 teachers in collaboration with the Princes Trust.');
addMarker(map, 'Online - Abraham Moss Primary School, Manchester', {lat: 53.512387,lng: -2.2357601}, '8 June 2021', 'Helen Schell and Helen Mason worked on the Mars Project with Year 5 and 6 students, involving 125 children and 10 teachers.');
addMarker(map, 'Online - Gillespie Primary School , London', {lat: 51.559719,lng: -0.10102196}, '10 June 2021', 'An online Science for Life Network of teachers hosted by Gillespie Primary School in Islington included a SunSpaceArt CPD session led by Helen Schell and Helen Mason, with the participation of 20 teachers from different schools.');
addMarker(map, 'Llanishan Hearing Impaired Unit, Wales', {lat: 51.532402,lng: -3.1873614}, '22 June 2021', 'Emma Wride (AstroCymru) conducted a \'2D/3D collages\' workshop for KS3 students (Years 7-9) with 12 students and 2 teachers.');
addMarker(map, 'Queen Elizabeth II Conference Centre, London', {lat: 51.500701,lng: -0.12902186}, '29 June 2021', 'The Sir Arthur Clarke Gala Dinner recognised SunSpaceArt\'s achievement with the 2020 Arthur C. Clarke Group Award for Space Achievement in Education and Outreach, attended by many influential people, representatives from the Space Industry, and scientists.');
addMarker(map, 'Heolddu Learning Pathway Canter, Wales', {lat: 51.688311,lng: -3.2445586}, '6 July 2021', 'Emma Wride (AstroCymru) ran a \'2D/3D Collages\' workshop for 11-16-year-olds with 15 students and 2 teachers.');
addMarker(map, 'Ty Gwyn Education Center, Wales', {lat: 51.721356,lng: -3.4644645}, '13 July 2021', 'Emma Wride (AstroCymru) ran a \'2D/3D collages\' workshop for 11 - 16-year-olds, with 20 students and 2 teachers.');
addMarker(map, 'YGG Bronllwyn, Wales', {lat: 51.642194,lng: -3.4843275}, '14 July 2021', 'Emma Wride (AstroCymru) ran a \'2D/3D collages/Pop-Up books\' workshop for Year 5 students, involving 27 children and 2 teachers.');
addMarker(map, 'Llandeilo Primary School, Wales', {lat: 51.887539,lng: -3.9894134}, '14 September 2021', 'Emma Wride (AstroCymru) gave a \'Space Careers\' presentation to Year 4, 5, and 6 students, engaging 90 students and 4 teachers.');
addMarker(map, 'STEMFest North East, Sunderland', {lat: 54.912783,lng: -1.3708813}, '7 October 2021', 'STEMFest North East reached 1000 children with an \'Art in Space\' session led by Helen Schell and Helen Mason, and a workshop led by Emma Wride (AstroCymru) and Sarah Bridgland with Year 3 students, involving 32 children and 2 teachers.');
addMarker(map, 'Allensbank Primary School, Wales', {lat: 51.502091,lng: -3.1855503}, '20 October 2021', 'Emma Wride (AstroCymru) ran a workshop for Year 3 students with 32 children and 2 teachers.');
addMarker(map, 'Bloomsbury Festival, London', {lat: 51.520997,lng: -0.12784422}, '23 October 2021', 'At the Bloomsbury Festival, SunSpaceArt activities organised and run by Krishna Mooroogen, Alice White, Christabel Forbes, and Sehar Sheikh featured a \'Space Exploration Pop-Up\' session with approximately 200 participants, including adults and children. The festival also generated follow-up requests from schools for SSA workshops.');
addMarker(map, 'Penywaun Primary School, Wales', {lat: 51.731624,lng: -3.480986}, '2 November 2021', 'Emma Wride (AstroCymru) and Sarah Bridgland ran an \'Art in Space\' workshop for autistic children in Years 5 and 6, involving 46 children and 2 teachers.');
addMarker(map, 'Bryn Awel Primary School, Wales', {lat: 51.755268,lng: -3.2776352}, '9 November 2021', 'Emma Wride (AstroCymru) and Sarah Bridgland ran an \'Art in Space\' workshop for Year 5 and 6 students, with 35 children and 2 teachers.');
addMarker(map, 'Ysgol Llyn Y Forwen, Wales', {lat: 51.658302,lng: -3.4501996}, '2 December 2021', 'Emma Wride (AstroCymru) and Sarah Bridgland delivered a \'What is Space?\' workshop for Year 3 and 4 students, engaging 60 children and 4 teachers, in association with the James Web Space Telescope (JWST).');
addMarker(map, 'Local Enterprise Partnership (LEP) North East, North East', {lat: 54.966403,lng: -1.6224219}, '10 January 2022', 'An online careers and enterprise talk was delivered to Local Enterprise Partnership (LEP) school liaison individuals, focusing on careers in the space industry. The session was led by Helen Schell, with Helen Mason and Mark Fox as facilitators. The event included 20 LEP representatives representing 200 North East schools.');
addMarker(map, 'Redditch Astro Society, ', {lat: 52.305143,lng: -1.9381967}, '10 January 2022', 'An online talk titled \'Reaching for the Sun\' was given by Helen Mason and attended by 30 astronomers.');
addMarker(map, 'St Augustine\'s Catholic High School, ', {lat: 52.271622,lng: -1.9468456}, '10 January 2022', 'An online talk titled \'Reaching for the Sun\' was given by Helen Mason and attended by 30 astronomers.');
addMarker(map, 'Online - LEP schools, Bolton', {lat: 54.966403,lng: -1.6225219}, '10 January 2022', 'A Careers and Enterprise Talk for Local Enterprise Partnership (LEP) school liaison individuals about careers in the space industry, was given by Helen Schell, with Mark Fox as the facilitator. The event included 20 LEP individuals representing 200 schools in the North East.');
addMarker(map, 'Online - Bolton Schools, Bolton', {lat: 53.552369,lng: -2.5222595}, '19 January 2022', 'An online talk about \'The Sun, our star\' was delivered by Helen Mason to schools in Bolton. The teacher contact for this event was Bernie Furey from Sacred Heart Roman Catholic Primary School. The session involved 200 primary school children from Years 4-6, accompanied by 25 teachers from several schools in Greater Manchester.');
addMarker(map, 'Online - STFC meeting, National', {lat: 51.566838,lng: -1.785952}, '20 January 2022', 'During an Science and Technology Facilities Council (STFC) Grant holder’s zoom meeting, Emma Wride (AstroCymru) discussed her work with schools in Wales, including the SunSpaceArt workshops.');
addMarker(map, 'Litchard Primary School, Wales', {lat: 51.522503,lng: -3.5778297}, '24 January 2022', 'Emma Wride (AstroCymru) and Sarah Bridgland conducted a \'What is Space?\' workshop with 57 children in Year 6, along with 4 teachers, in association with the  James Webb Space Telescope (JWST).');
addMarker(map, 'Bryn Bach Primary School, Wales', {lat: 51.786004,lng: -3.2598158}, '26 January 2022', 'An online \'Collages 2D/3D\' workshop was led by Emma Wride (AstroCymru), involving 30 students and 2 teachers.');
addMarker(map, 'St Peter’s Church of England Primary School, Lancashire', {lat: 53.66092,lng: -2.6182486}, '26 January 2022', 'Helen Schell and Helen Mason led a workshop on \'Flags of the Solar System.\' Kat Gallager was the teacher for this event, which involved Year 5 and 6 students, totaling 110 children and 4 teachers.');
addMarker(map, 'Online - Association for Science Education (ASE)  , National', {lat: 51.752896,lng: -0.24308238}, '28 January 2022', 'At the ASE (Association for Science Educators) TeachMeet, an online short talk about the SunSpaceArt project was delivered by Helen Mason, and it was attended by 30 primary school teachers.');
addMarker(map, 'Ysgol Penalltau, Wales', {lat: 51.65557,lng: -3.2439505}, '7 February 2022', 'Emma Wride (AstroCymru) and Sarah Bridgland ran a \'2D/3D collages\' workshop for 30 Year 6 students, along with 2 teachers. ');
addMarker(map, 'Gwaun Y Nant, Wales', {lat: 51.416743,lng: -3.2677264}, '8 February 2022', 'Emma Wride (AstroCymru)  and Sarah Bridgland ran a \'2D/3D collages\' workshop for Year 3 students, involving 30 children and 2 teachers.');
addMarker(map, 'Rossett Acre Primary School	, Harrogate, Yorks', {lat: 53.977695,lng: -1.5509679}, '16 February 2022', 'Helen Mason led two online assemblies for the whole school, totaling 200 children and 10 teachers. ');
addMarker(map, 'Radio Wiltshire, Wiltshire', {lat: 51.554019,lng: -1.7776322}, '21 February 2022', 'Helen Schell and Helen Mason participated in a Radio Wiltshire interview for the Festival of Tomorrow.');
addMarker(map, 'Deanery CE Academy, Swindon', {lat: 51.545425,lng: -1.8095001}, '25 February 2022', 'The Festival of Tomorrow featured a \'Solar display\' by Robert Walsh and SunSpaceArt workshops, including Solar Pop-up cards. Helen Schell collaborated with artist Ione Parker (Bath), and Helen Mason also participated. This event was funded by the Science and Technology Facilities Council (STFC) and had an estimated 400 participants over two days. Additionally, 150 STFC Sun and other leaflets were distributed.');
addMarker(map, 'Deanery CE Academy, Swindon', {lat: 51.545425,lng: -1.8096001}, '26 February 2022', 'The Festival of Tomorrow featured a \'Solar display\' by Robert Walsh and SunSpaceArt workshops, including Solar Pop-up cards. Helen Schell collaborated with artist Ione Parker (Bath), and Helen Mason also participated. This event was funded by the Science and Technology Facilities Council (STFC) and had an estimated 400 participants over two days. Additionally, 150 STFC Sun and other leaflets were distributed.');
addMarker(map, 'Argyle Primary School, Camden', {lat: 51.528748,lng: -0.12390759}, '2 March 2022', 'Clare Dudeney, Helen Mason, Christabel Forbes, Rebecca Chucks (literacy expert), and Dr. John Dudeney (polar expert) ran a SunSpaceArt workshop on Antarctica with Year 6 students led by teacher Helene Taylor, Approximately 60 children and 4 teachers participated.');
addMarker(map, 'Online - International Astronomical Union, International', {lat: 48.8498721,lng: 2.2834956}, '8 March 2022', 'The International Astronomical Union (IAU) hosted an \'Enterprising Women\' event featuring an online talk by Helen Mason, which attracted 40 participants and was also available on YouTube.');
addMarker(map, 'Association for Science Education (ASE), Norwich', {lat: 52.62237,lng: 1.241391}, '9 March 2022', 'At the Association for Science Educators (ASE) East Anglia TeachMeet during UK Science Week, Helen Mason gave a short talk that was attended by 10 teachers.');
addMarker(map, 'Southmoor Academy, Sunderland', {lat: 54.890587,lng: -1.3761847}, '16 March 2022', 'Helen Schell ran a \'Make It to Mars Challenge\' workshop as part of Mars Day/Week. This initiative involved Year 9 students, with 25 participants');
addMarker(map, 'Milton Rd Primary School, Cambridge', {lat: 52.218502,lng: 0.12773755}, '29 March 2022', 'SunSpaceArt astronomy and art activities took place with Matt Bothwell, the Public Astronomer from the Institute of Astronomy (IoA) at Cambridge. The SSA team, including Helen Mason, Clare Dudeney, Christabel Forbes, and local artist Maria Merridan, engaged with Year 5 and 6 students, totaling 120 children and 6 teachers. ');
addMarker(map, 'Institute of Astronomy (IoA), Cambridge', {lat: 52.214532,lng: 0.095328164}, '9 April 2022', 'SunSpaceArt family workshops were run at the Cambridge Festival\'s Institute of Astronomy (IoA) Open Day led by Matt Bothwell. These  workshops were organised by Helen Mason, with Clare Dudeney and two young researchers from the IoA and Department of Applied Mathematics and Theoretical Physics (DAMTP). Families took part, with approximately 200 participants. Additionally, 100 STFC Sun and other leaflets were distributed.');
addMarker(map, 'Abraham Moss Community School, Manchester', {lat: 53.512387,lng: -2.2358601}, '26 April 2022', 'Helen Schell and Helen Mason led \'Sun & Moon\' workshops for Year 5 students, in collaboration with the Comino Foundation and coordinated by Deborah Davidson. A total of 60 children and 3 teachers participated.');
addMarker(map, 'St Kentigern’s Primary School, Manchester', {lat: 53.442474,lng: -2.2360348}, '26 April 2022', 'Helen Schell and Helen Mason led \'Sun & Moon\' workshops for Year 5 students, in collaboration with the Comino Foundation and coordinated by Deborah Davidson. A total of 60 children and 3 teachers participated.');
addMarker(map, 'Sacred Heart Primary School, Bolton', {lat: 53.552369,lng: -2.5223595}, '27 April 2022', 'The Heart Teaching Alliance, in collaboration with the Comino Foundation, organised Continuing Professional Development (CPD) sessions for trainee teachers from Sacred Heart Primary School in Bolton. The \'Sun & Moon\' CPD was led by Helen Schell and Helen Mason and involved 10 trainee teachers over a span of 2 days.');
addMarker(map, 'Argyle Primary School, Camden', {lat: 51.528748,lng: -0.12400759}, '29 April 2022', 'A Shadow Puppet workshop was led by Christabel Forbes with Helen Mason, Clare Dudeney, and Rebecca Chucks (literacy expert) for Year 4 students. The session engaged 30 children and 2 teachers, including lead teach Helene Taylor.');
addMarker(map, 'Association for Science Education (ASE) South East, South East', {lat: 51.752876,lng: -0.24217323}, '4 May 2022', 'Helen Mason gave a talk as part of an online primary TeachMeet hosted by the Association for Science Educators (ASE) South East - Beds, Herts, Cambs. The tqlk was that was attended by 15 teachers.');
addMarker(map, 'Swansea Astro Club, Wales', {lat: 51.622052,lng: -3.9425408}, '5 May 2022', 'Helen Mason delivered a talk on Solar Space Observations to the Swansea Astro Club, attracting 30 amateur astronomers.');
addMarker(map, 'Gainsborough Primary School,, London', {lat: 51.546037,lng: -0.026104091}, '17 May 2022', 'Geraldine Cox led \'The Sun\' workshop, with Dr. Ravi Desai (solar scientist), engaging two groups of 30 children (aged 8-9-year-old), and 2 teachers.');
addMarker(map, 'Morningside Primary School,, London', {lat: 51.546504,lng: -0.050285228}, '18 May 2022', 'Geraldine Cox led \'The Sun\' workshop, with Dr. Ravi Desai (solar scientist), engaging 30 children (aged 8-9-year-old), and four teachers.');
addMarker(map, 'De Beauvoir Primary School, London', {lat: 51.545359,lng: -0.077347205}, '23 May 2022', 'A \'Magnets and the Sun\' workshop was led by Geraldine Cox with Steph Yardley (solar scientists), 30 students aged 7-9 years and 2 teachers.');
addMarker(map, 'Trerobart Primary School, Wales', {lat: 51.636661,lng: -3.3598298}, '24 May 2022', 'Emma Wride (AstroCymru)  conducted a \'2D/3D\' workshop for Year 6 students, engaging 48 students and 4 teachers. ');
addMarker(map, 'Keir Hardie Primary School , London', {lat: 51.516497,lng: 0.020326594}, '10 June 2022', 'An \'Our Place in the Universe\' workshop was led by Helen Mason, with support from Christabel Forbes and Clare Dudeney, and coordinated by Francis Moore, engaging 60 Year 5 children and 4 teachers.');
addMarker(map, 'St John and St James Primary School,, London', {lat: 51.548072,lng: -0.049958563}, '10 June 2022', 'A \'Sound and Vibrations\' workshop was led by Dagny Kimberly Yousuf, accompanied by Prof Jonathan Halliwell from Imperial College. This session engaged 30 students aged 8-10, along with 4 teachers.');
addMarker(map, 'Online - Wells & Medip Astronomy Club, Somerset', {lat: 51.210545,lng: -2.6462047}, '11 June 2022', 'The Wells and Medip Astronomy Club organised an online event featuring a talk by Helen Mason, which attracted 30 amateur astronomers.');
addMarker(map, 'Eastbrooke Primary School, London', {lat: 51.551475,lng: 0.16369855}, '14 June 2022', 'The Great Science Share for Schools, organised by Kulvinder Johal at Eastbrooke Primary School in Dagenham, included SunSpaceArt activities led by Helen Mason, John Dudeney, Clare Dudeney, Clare Davidson (Sustainability First), and Anthony Garratt (artist, Cornwall). This event involved 5 schools, spanning Year 3-6 students, with a total of 67 children and 10 teachers participating.');
addMarker(map, 'Gascoigne Primary School, London', {lat: 55.881312,lng: -4.3258418}, '14 June 2022', 'The Great Science Share for Schools, organised by Kulvinder Johal at Eastbrooke Primary School in Dagenham, included SunSpaceArt activities led by Helen Mason, John Dudeney, Clare Dudeney, Clare Davidson (Sustainability First), and Anthony Garratt (artist, Cornwall). This event involved 5 schools, spanning Year 3-6 students, with a total of 67 children and 10 teachers participating.');
addMarker(map, 'Grafton Primary School, London', {lat: 51.55839,lng: 0.13971744}, '14 June 2022', 'The Great Science Share for Schools, organised by Kulvinder Johal at Eastbrooke Primary School in Dagenham, included SunSpaceArt activities led by Helen Mason, John Dudeney, Clare Dudeney, Clare Davidson (Sustainability First), and Anthony Garratt (artist, Cornwall). This event involved 5 schools, spanning Year 3-6 students, with a total of 67 children and 10 teachers participating.');
addMarker(map, 'Hunters Hall Primary School, London', {lat: 51.547299,lng: 0.15605793}, '14 June 2022', 'The Great Science Share for Schools, organised by Kulvinder Johal at Eastbrooke Primary School in Dagenham, included SunSpaceArt activities led by Helen Mason, John Dudeney, Clare Dudeney, Clare Davidson (Sustainability First), and Anthony Garratt (artist, Cornwall). This event involved 5 schools, spanning Year 3-6 students, with a total of 67 children and 10 teachers participating.');
addMarker(map, 'Sandringham Primary School, London', {lat: 51.546769,lng: 0.034720177}, '14 June 2022', 'The Great Science Share for Schools, organised by Kulvinder Johal at Eastbrooke Primary School in Dagenham, included SunSpaceArt activities led by Helen Mason, John Dudeney, Clare Dudeney, Clare Davidson (Sustainability First), and Anthony Garratt (artist, Cornwall). This event involved 5 schools, spanning Year 3-6 students, with a total of 67 children and 10 teachers participating.');
addMarker(map, 'Bryn Bach Primary School, ‘2D/3D’, Wales', {lat: 51.786004,lng: -3.2599158}, '20 June 2022', 'Emma Wride (AstroCymru) and Sarah Bridgland conducted a workshop for Year 5 students, involving 30 children and 2 teachers.');
addMarker(map, 'Cité internationale universitaire de Paris, Paris', {lat: 48.8199761,lng: 2.3387146}, '28 June 2022', 'At the Loops10 Workshop, Helen Mason gave a talk about SunSpaceArt, engaging 80 professional solar scientists.');
addMarker(map, 'St Kentigern’s Primary School, Manchester', {lat: 53.442474,lng: -2.2361348}, '6 July 2022', 'Helen Schell led a \'Moon Village\' workshop in collaboration with Helen Mason (online), facilitated by Deborah Davidson, and supported by the Comino Foundation. The workshop had active participation from 60 Year 5 students and was overseen by four teachers.');
addMarker(map, 'University of Warwick, Coventry', {lat: 52.373734,lng: -1.5523447}, '13 July 2022', 'The team ran SunSpaceArt family drop in session at the Science Festival for National Astronomy Meeting (NAM), with about 80 participants. 300 booklets from the Science and Technology Facilities Council (STFC) were distributed.');
addMarker(map, 'Hearshall Academy, Coventry', {lat: 52.404558,lng: -1.5305723}, '11 July 2022', 'The National Astronomy Meeting (NAM) held at the University of Warwick featured SSA workshops in collaboration with the SUN installation at NAM, led by Robert Walsh. Schools were brought into Warwick University, and the workshops were led by Helen Mason, with participation from Clare Dudeney, Helen Schell, and young solar researchers, including Martin Farnir, Faith Hawthorn, Marina Lafargo Magro, Anne-Maria Broomhall, and Deanne Coppejans. This initiative was funded directly by the Science and Technology Facilities Council (STFC).');
addMarker(map, 'Templars Primary School, Coventry', {lat: 52.400529,lng: -1.572827}, '12 July 2022', 'The National Astronomy Meeting (NAM) held at the University of Warwick featured SSA workshops in collaboration with the SUN installation at NAM, led by Robert Walsh. Schools were brought into Warwick University, and the workshops were led by Helen Mason, with participation from Clare Dudeney, Helen Schell, and young solar researchers, including Martin Farnir, Faith Hawthorn, Marina Lafargo Magro, Anne-Maria Broomhall, and Deanne Coppejans. This initiative was funded directly by the Science and Technology Facilities Council (STFC).');
addMarker(map, 'Allesley Primary School, Coventry', {lat: 52.427381,lng: -1.5674644}, '13 July 2022', 'The National Astronomy Meeting (NAM) held at the University of Warwick featured SSA workshops in collaboration with the SUN installation at NAM, led by Robert Walsh. Schools were brought into Warwick University, and the workshops were led by Helen Mason, with participation from Clare Dudeney, Helen Schell, and young solar researchers, including Martin Farnir, Faith Hawthorn, Marina Lafargo Magro, Anne-Maria Broomhall, and Deanne Coppejans. This initiative was funded directly by the Science and Technology Facilities Council (STFC).');
addMarker(map, 'National Astronomy Meeting (NAM), Coventry', {lat: 52.373734,lng: -1.5524447}, '14 July 2022', 'Helen Mason gave a talk about SunSpaceArt during the National Astronomy Meeting (NAM), with 40 participants.');
addMarker(map, 'Whoberley Hall Primary School, Coventry', {lat: 52.409953,lng: -1.5539189}, '14 July 2022', 'The National Astronomy Meeting (NAM) held at the University of Warwick featured SSA workshops in collaboration with the SUN installation at NAM, led by Robert Walsh. Schools were brought into Warwick University, and the workshops were led by Helen Mason, with participation from Clare Dudeney, Helen Schell, and young solar researchers, including Martin Farnir, Faith Hawthorn, Marina Lafargo Magro, Anne-Maria Broomhall, and Deanne Coppejans. This initiative was funded directly by the Science and Technology Facilities Council (STFC).');
addMarker(map, 'Centre 4 Life, Newcastle', {lat: 54.967559,lng: -1.6211928}, '20 July 2022', 'The STEM Northeast women\'s group organised a Moon talk and workshop, with Helen Schell and Lorraine Coghill participating. The discussion also included information on SunSpaceArt, with 20 participants.');
addMarker(map, 'Institute of Astronomy (IoA), Cambridge', {lat: 52.209216,lng: 0.13054321}, '30 July 2022', 'Our Place in Space featured a scale model of the Solar System and SunSpaceArt family workshops, including \'Pop-Up cards of the Solar System.\' Alice White, Maria Merridan, Maggie Goulden (Institute of Astronomy, PhD student), and Yamini Rao (DAMTP, post-doc) were involved, along with Helen Mason and Matt Bothwell (Institute of Astronomy). This event engaged 500 participants over two days, primarily families, and was funded by Unboxed.');
addMarker(map, 'Institute of Astronomy (IoA), Cambridge', {lat: 52.209216,lng: 0.13044321}, '31 July 2022', 'Our Place in Space featured a scale model of the Solar System and SunSpaceArt family workshops, including \'Pop-Up cards of the Solar System.\' Alice White, Maria Merridan, Maggie Goulden (Institute of Astronomy, PhD student), and Yamini Rao (DAMTP, post-doc) were involved, along with Helen Mason and Matt Bothwell (Institute of Astronomy). This event engaged 500 participants over two days, primarily families, and was funded by Unboxed.');
addMarker(map, 'Institute of Astronomy (IoA), Cambridge', {lat: 52.209216,lng: 0.13034321}, '28 August 2022', 'During the \'Our Place in Space\' family sessions, the SunSpaceArt team organised a "Flags of the Solar System" workshop involving Helen Mason, Alice White, Maria Merridan, Maggie Goulden (Institute of Astronomy PhD student), and Jonathan Worden (young scientist). We had 100 participating families and distributed 200 Science and Technology Facilities Council (STFC) Sun, and other booklets.');
addMarker(map, 'Slough library , Slough', {lat: 51.509798,lng: -0.59498979}, '3 September 2022', 'Helen Mason ran a workshop as part of Story Trails with 50 members of the public.');
addMarker(map, 'Slough library , Slough', {lat: 51.509798,lng: -0.59508979}, '4 September 2022', 'Helen Mason was featured as part of Story Trails conducted the "Slough into Space" project, a major national, interactive, immersive experience for families. Sponsored by Unboxed, this project included workshops at Slough library, led by Helen Mason and John Dudeney, and interacted with approximately 100 people, both adults and children. Additionally, 100 STFC Sun and other brochures were distributed.');
addMarker(map, 'INTERACT - Cardiff City Hall, Wales', {lat: 51.485148,lng: -3.1786442}, '13 September 2022', 'INTERACT, organised by the Science and Technology Facilities Council (STFC) and the Institute of Physics (IoP) and featuring Robert Walsh discussing the Sun, involved participation from the SunSpaceArt team, including Emma Wride (AstroCymru) delivering a talk and Helen Mason overseeing a table in the Market Place, along with Heather MacRae. The event involved interaction with approximately 100 science communication specialists and academics.');
addMarker(map, 'Online - Astroclub, Wales', {lat: 51.406743,lng: -3.2669609}, '26 September 2022', 'Helen Mason had a talk and interaction table at the On-line Astro Club event with 30 members.');
addMarker(map, 'University of Leicester, Leicester', {lat: 52.621919,lng: -1.1239104}, '22 October 2022', 'The Wonder Initiative Science and Technology Facilities Council (STFC) Sparks workshop for the Somali Community, led by Sarah Langford of SphereScience, included a workshop by Helen Mason and engaged 10 youths.');
addMarker(map, 'Penrhys Primary School, Rhondda', {lat: 51.644198,lng: -3.4403261}, '9 November 2022', 'Emma Wride (AstroCymru) and Sarah Bridgland conducted a workshop for Year 2, 3, 4, 5, and 6 students, involving 60 children and 8 teachers.');
addMarker(map, 'Institute of Physics (IoP), London', {lat: 51.532504,lng: -0.12033608}, '17 November 2022', 'Helen Mason delivered a talk on the SunSpaceArt project and Geraldine Cox presented a talk on \'The Gifts\' to an audience consisting of 50 science communicators and academics.');
addMarker(map, 'Institute of Astronomy, Cambridge', {lat: 52.214532,lng: 0.095228164}, '30 November 2022', 'Yamini Rao, who is Helen Mason\'s postdoctoral researcher, delivered a public talk about the Sun to an audience of 50 members of the public.');
addMarker(map, 'Glasgow Science Centre, Glasgow', {lat: 55.858805,lng: -4.2948852}, '25 January 2023', 'Helen Mason attended an Royal Astronomical Society (RAS) outreach event.');
addMarker(map, 'Abraham Moss Community School, Manchester', {lat: 53.512387,lng: -2.2359601}, '31 January 2023', 'A SunSpaceArt workshop on \'Sun Pop-Up cards\' was led by Helen Mason and Helen Schell. This workshop was co-funded by the Comino Foundation and involved Year 5 students from 2 classes.');
addMarker(map, 'Aberdare Town Church Primary School, Wales', {lat: 51.709378,lng: -3.4405145}, '1 February 2023', 'Sarah Bridgland and Emma Wride (AstroCymru) delivered SunSpaceArt workshops to Year 3, 4, and 5 students, totaling 90 pupils.');
addMarker(map, 'Royal Astronomical Society (RAS), London', {lat: 51.508576,lng: -0.13980806}, '10 February 2023', 'Helen Mason attended an Royal Astronomical Society (RAS) outreach event.');
addMarker(map, 'STEAM Museum, Swindon', {lat: 51.563357,lng: -1.7954319}, '17 February 2023', 'At the \'Festival of Tomorrow\' held at the STEAM museum, SunSpaceArt workshops related to the Sun were conducted by Emma Wride and Sarah Bridgland, engaging 500 people over two days.');
addMarker(map, 'STEAM Museum, Swindon', {lat: 51.563357,lng: -1.7955319}, '18 February 2023', 'At the \'Festival of Tomorrow\' held at the STEAM museum, SunSpaceArt workshops related to the Sun were conducted by Emma Wride and Sarah Bridgland, engaging 500 people over two days.');
addMarker(map, 'Indian Institutes of Science Education and Research (ISSER), India', {lat: 18.5474356,lng: 73.8053994}, '27 February 2023', 'Helen Mason gave a talk to the Indian Institutes of Science Education and Research (ISSER) to the Astro Club. ');
addMarker(map, 'Pune, India', {lat: 18.516726,lng: 73.856255}, '28 February 2023', 'Helen Mason visited India, including the Inter-University Centre for Astronomy and Astrophysics (IUCAA) and the Indian Institutes of Science Education and Research (ISSER) in Pune, where she participated in the Indian National Science Day, working with thousands of students and children.');
addMarker(map, 'Vellore Institute of Technology (VIT) Bhopal, India', {lat: 23.0774715,lng: 76.8512871}, '1 March 2023', 'Helen Mason delivered an online talk titled "Solar Spectroscopy in the UV and X-rays" during National Science Week at Vellore Institute of Technology (VIT) Bhopal, reaching 200 university and upper school students.');
addMarker(map, 'Harris Academy Primary School, Tottenham, London', {lat: 51.591837,lng: -0.060154195}, '14 March 2023', 'Helen Mason gave an online talk about the Sun and being a scientist to 30 children and 1 teacher.');
addMarker(map, 'Institute of Astronomy (IoA), Cambridge', {lat: 52.214532,lng: 0.095128164}, '18 March 2023', 'At the Cambridge Festival and Institute of Astronomy (IoA) Open Day, SunSpaceArt family "drop-in workshops" were held in collaboration with Matt Bothwell from IoA. This event saw 500 participants.');
addMarker(map, 'Number One Riverside, Rochdale', {lat: 53.617565,lng: -2.1558332}, '19 March 2023', 'The Rochdale Science Initiative Extravaganza featured \'Spiral of Voices,\' a workshop conducted by Geraldine Cox.');
addMarker(map, 'Wymondham College, Norfolk ', {lat: 52.544907,lng: 1.057359}, '22 March 2023', 'Helen Mason delivered a talk to sixth form students.');
addMarker(map, 'Institute of Astronomy (IoA), Cambridge', {lat: 52.214532,lng: 0.095028164}, '25 March 2023', 'During the Cambridge Festival Family Weekend, SunSpaceArt family workshops on \'Pop-up cards\' and \'Flags of the Solar System\' were led by Maria Merridan, with the participation of Helen Mason and several young astronomy researchers, engaging 300 participants.');
addMarker(map, 'Institute of Astronomy (IoA), Cambridge', {lat: 52.214532,lng: 0.094928164}, '26 March 2023', 'During the Cambridge Festival Family Weekend, SunSpaceArt family workshops on \'Pop-up cards\' and \'Flags of the Solar System\' were led by Maria Merridan, with the participation of Helen Mason and several young astronomy researchers, engaging 300 participants.');
addMarker(map, 'Sacred Heart Primary School, Bolton', {lat: 53.552369,lng: -2.5224595}, '20 April 2023', 'Helen Mason and Clare Dudeney ran a Continued Professional Development (CPD) event on the Sun involving 25 trainee teachers with the Teaching Alliance.');
addMarker(map, 'Cambridge Stroke Group, Great Shelford', {lat: 52.158716,lng: 0.12665371}, '27 April 2023', 'Helen Mason gave a talk about \'The Sun, our star\' to a \'Stroke\' group, with 25 participants with disabilities.');
addMarker(map, 'Cheltenham Science Festival, Cheltenham', {lat: 51.897223,lng: -2.077704}, '8 June 2023', 'The Cheltenham Science Festival featured a SunSpaceArt workshops with the theme \'Out of this World Art\' organised by Helen Mason, Emma Wride (AstroCymru), and Sarah Bridgland.');
addMarker(map, 'Queen Mary College, London, ', {lat: 51.52341,lng: -0.040532343}, '13 June 2023', 'The Great Science Share for Schools at Queen Mary University of London (QMUL) involved six schools and was led by Kulvinder Johal. Helen Mason had a table with science interactions using UV beads, engaging approximately 60 children from local schools.');
addMarker(map, 'Hertford Astronomy Club, Hertford', {lat: 51.752896,lng: -0.24318238}, '14 June 2023', 'The Herts Astro Club hosted a talk by Helen Mason titled \'Reaching for our Sun,\' with 40 in-person participants and 20 online attendees.');
addMarker(map, 'Alice Ingham RC Primary School, Rochdale', {lat: 53.630207,lng: -2.1368721}, '22 June 2023', 'Our Sun and Earth\' was led by Geraldine Cox with the participation of Helen Mason for Year 5 students, with 30 children and 2 teachers.');
addMarker(map, 'Cardiff University, Cardiff', {lat: 51.489066,lng: -3.1799111}, '6 July 2023', 'At the National Astronomy Meeting, Geraldine Cox gave a talk and participated in a panel discussion, while Emma Wride (AstroCymru) delivered a talk. Sarah Bridgland and Helen Mason led a \'drop-in\' Sun/Art family session.');
addMarker(map, 'STFC Daresbury , Warrington', {lat: 53.343404,lng: -2.641206}, '10 July 2023', 'During the Science and Technology Facilities Council (STFC) Daresbury Lab Open Day, the team ran SunSpaceArt workshops for years 4 and 5, involving 100 children and 5 teachers.');
addMarker(map, 'STFC Daresbury , Warrington', {lat: 53.343404,lng: -2.641306}, '15 July 2023', 'The team ran SunSpaceArt family drop in sessions, with about 250 participants, as part of Science and Technology Facilities Council (STFC) Daresbury.');
addMarker(map, 'Durham University, National', {lat: 54.768139,lng: -1.5718583}, '1 July 2020', 'Helen Schell shared SunSpaceArt related links for activities including "Bring It On/Engineering Together" in the Southeast (SE) region, in collaboration with Durham University\'s Ogden Centre for Fundamental Physics and Durham Arts Education, which have had a wide-ranging impact on hundreds of individuals locally and nationally.');
addMarker(map, 'Association for Science Education (ASE), National', {lat: 51.752896,lng: -0.24298238}, '1 January 2022', 'Helen Mason authored an article on "The Art and Science of Creativity" in Association for Science Education (ASE) Primary Science Magazine, reaching hundreds of primary school teachers.');